knowledge_vertices = {	'Tỷ lệ trích lập dự phòng': [
		'0%',
		'5%',
		'20%',
		'50%',
		'100%',
	],
	'Tổng quan về công ty': [
		'Sứ mệnh',
		'Quy mô phát tiển tại Việt Nam',
		'Cột mốc phát triển',
		'Lịch sử thành lập',
		'Tầm nhìn',
		'Thành tựu nổi bật',
		'Đối tác',
		'Khách hàng của ngân hàng',
		'Khách hàng đủ điều kiện làm hợp đồng với Home Credit',
	],
	'Chi tiết công ty': [
		'Mang lại những dịch vụ tài chính đáng tin cậy tới cho khách hàng và đối tác để tiếp cận thông qua các kênh tùy chọn|Liên tục đáp ứng những nhu cầu mới, dù là trực tiếp hay qua những hệ sinh thái đột phá, góp phần xây dựng một thế giới vững mạnh hơn',
		'Là một trong những công ty hàng đầu trong lĩnh vực tài chính tiêu dùng, hiện có trụ sở chính tại TP.HCM và văn phòng đại diện tại 10 tỉnh thành trên toàn quốc|Mạng lưới 9.000 điểm bán lẻ tại 63 tỉnh thành trên toàn quốc, phục vụ hơn 13 triệu khách hàng, đã có 8,3 triệu lượt tải ứng dụng Home Credit trên điện thoại',
		'Được cấp giấy phép vào năm 2008, đến năm 2009 công ty chính thức ra mắt thương hiệu và triển khai sản phẩm đầu tiên|Cuối năm 2022, đẩy mạnh phát triển theo hướng số hóa, ra mắt ứng dụng trên điện thoại giúp KH có thể thực hiện và theo dõi khoản vay trực tuyến dễ dàng',
		'Tập đoàn Home Credit được thành lập năm 1997 ở Cộng Hòa Czech. Cho đến nay, Home Credit đã trở thành một trong những tập đoàn hàng đầu thế giới về lĩnh vực cho vay tài chính tiêu dùng|Hiện nay Home Credit đang phục vụ cho hơn 141 triệu khách hàng; hơn 98 triệu người dùng ứng dụng với gần 42 ngàn hợp đồng được tạo mới mỗi ngày|Những quốc gia, vùng lãnh thổ đã có sự xuất hiện của Home Credit trên 10 năm là: Philipine, Indonesia, India, China, Việt Nam',
		'Giúp khách hàng làm chủ cuộc sống và sống vui như mong đợi',
		'Giải thưởng top 100 công ty có môi trường làm việc tốt nhất khu vực châu Á – Thái Bình Dương năm 2021|Giải thưởng Golden Dragon Awards 2021 dành cho doanh nghiệp tiên phong đổi mới, sáng tạo, ứng dụng công nghệ vào quy trình kinh doanh và quản trị doanh nghiệp|Giải thưởng doanh nghiệp Bắc Âu 2021 dành cho doanh nghiệp FDI có những sáng kiến, hỗ trợ và đóng góp tích cực trong đại dịch Covid-19 tại Việt Nam|Giải thưởng Inspirational Brand Award – Thương hiệu truyền cảm hứng, chỉ dành riêng cho những doanh nghiệp có thương hiệu sản phẩm dịch vụ truyền cảm hứng hoặc ảnh hưởng tích cực tới cộng đồng và được người tiêu dùng, công chúng tin tưởng lựa chọn, ủng hộ|Giải thưởng Visa Awards 2021 – của tổ chức Visa toàn cầu trao tặng cho doanh nghiệp có những đổi mới sáng tạo, tăng trưởng năng động và dịch vụ tốt nhất trong phân khúc|Giải thưởng The Global Economics Awards 2021 dành cho doanh nghiệp có đóng góp những thành tựu to lớn trong các lĩnh vực Ngân hàng, Tài chính, Bất động sản, Bảo hiểm, Năng lượng và Công nghệ',
		'Hợp tác với gần 13.000 cửa hàng bán lẻ xe máy, điện thoại di động, cửa hàng điện tử và các nhà sản xuất trên toàn quốc với các thương hiệu nổi tiếng như: Thế Giới Di Động, Samsung, Yamaha,…',
	],
	'Quy định': [
		'Tuân thủ về niêm yết tài liệu',
		'Tuân thủ về trưng bày POSM',
		'Tuân thủ về nguyên tắc tư vấn',
		'Ứng xử khi gặp cơ quan nhà nước và báo chí',
		'Tuân thủ Nghị định 91 về nguyên tắc gọi điện, email, gửi tin nhắn tư vấn, quảng cáo',
	],
	'Chi tiết quy định': [
		'Niêm yết các tài liệu: Thông tin lãi suất sản phẩm, phương pháp tính lãi, các loại phí, Hợp đồng theo mẫu, Điều kiện giao dịch chung, Các hình thức tiếp nhận góp ý, phản ánh, khiếu nại của KH, Tài liệu khác theo thông báo từ TINTIN',
		'Khi cửa hàng không cho phép trưng bày kệ A4, lưu trữ tài liệu trong bìa sổ Home Credit, luôn mở sổ và đặt trên bàn làm việc, đảm bảo luôn sẵn sàng để cung cấp cho KH, hoặc xuất trình cho các cơ quan chức năng khi có yêu cầu',
		'Giữ POSM của mình luôn đẹp, gọn gàng, sạch sẽ',
		'Trưng bày POSM đúng vị trí theo hướng dẫn',
		'Kiểm tra và thay mới các dụng cụ, tài liệu này khi có thông báo từ TINTIN',
		'Đảm bảo có xác nhận của KH về việc đã được công ty cung cấp đầy đủ thông tin để KH xem xét, quyết định trước khi ký kết hợp đồng',
		'Luôn giữ thái độ niềm nở, vui vẻ, hợp tác và bình tĩnh',
		'Chỉ được phép cung cấp những thông tin trong phạm vi trách nhiệm công việc, tuyệt đối không cung cấp thêm bất kỳ thông tin nào khác',
		'Tư vấn quyền và nghĩa vụ của KH vay tiêu dùng',
		'Tư vấn các biện pháp đôn đốc, thu hồi nợ',
		'Tư vấn biện pháp xử lý khi KH không thực hiện nghĩa vụ theo hợp đồng',
		'Tư vấn các hình thức tiếp nhận góp ý, phản ánh, khiếu nại của KH',
		'Chỉ gửi tin nhắn trong khoảng thời gian từ 07 - 22 giờ mỗi ngày, gọi điện thoại quảng cáo từ 08 - 17 giờ mỗi ngày trừ trường hợp đã có thỏa thuận khác với KH',
		'Không được gửi quá 03 tin nhắn quảng cáo tới 01 SĐT, 03 thư điện tử quảng cáo tới một địa chỉ email, 01 cuộc gọi điện thoại quảng cáo tới 01 SĐT trong vòng 24 giờ trừ trường hợp đã có thỏa thuận khác với KH',
		'Ngừng các cuộc gọi quảng cáo nếu KH yêu cầu',
		'Tuân thủ nghiêm ngặt các quy định về bảo mật và sử dụng thông tin khi được phân phối danh sách KH tiềm năng - lead',
		'Chỉ sử dụng thông tin lead cho các mục đích được chỉ dẫn cụ thể bởi Công ty',
		'Tuyệt đối không chia sẻ thông tin Lead với bất kỳ ai, kể cả đồng nghiệp',
		'Không trả lời trực tiếp, hướng dẫn KH liên hệ hotline khi có thắc mắc, yêu cầu về quyền chủ thể với dữ liệu cá nhân, chính sách của Công ty đối với việc bảo vệ và xử lý dữ liệu',
		'Không hứa hẹn hay đồng ý với KH, hướng dẫn KH liên hệ hotline khi có khiếu nại, phản ứng gay gắt yêu cầu thực hiện các quyền của chủ thể dữ liệu',
		'Ngay lập tức ngừng liên hệ với KH trên toàn bộ các kênh liên lạc, bao gồm cả mạng xã hội khi KH từ chối nhận thông tin',
		'Khi được hỏi thông tin khác về Home Credit, nếu là Cơ quan truyền thông, đưa liên hệ chị Trương Trang Trà My',
		'Khi được hỏi thông tin khác về Home Credit, nếu là Thanh tra Ngân hàng Nhà nước, cán bộ các cơ quan chức năng khác, đưa liên hệ anh Lê Đình Quang',
		'Xin thông tin của cán bộ hoặc phóng viên, gửi email thông báo cho Chuyên viên tuân thủ hoặc Phòng Truyền thông và email có thông báo cho Cấp quản lý trực tiếp',
	],
	'Tác phong SA': [
		'mang giày bít gót, bít mũi, kiểu dáng đơn giản, độ cao vừa phải đối với nữ và mang giầy tây đối với nam',
		'mặc đồng phục và mang thẻ nhân viên trong suốt thời gian làm việc',
		'giữ đồng phục sạch sẽ, gọn gàng, chỉnh tề',
		'cắt tóc ngắn, gọn gàng đối với nam và cột tóc gọn, có thể nhuộm tóc, nhưng chọn màu tối đối với nữ',
		'mặc quần, váy bằng chất liệu jean, thun hoặc kiểu dáng thể thao, quá chật hoặc quá rộng',
		'mang giày thể thao, giày cao su, dép kẹp, giày quá nhiều màu nổi bật',
		'dùng đồ trang sức, phụ kiện, nước hoa quá mức',
		'mặc áo sơ mi đồng phục vào thứ 2 - thứ 7 và mặc áo thun Home Credit hoặc áo sơ mi đồng phục vào chủ nhật',
		'để màu tóc quá nổi bật hoặc kiểu tóc quá khác biệt',
	],
	'Nhóm sản phẩm': [
		'Vay trả góp mua hàng hóa tại shop',
		'Vay trả góp tiền mặt - CL',
		'Thẻ tín dụng - CC',
		'Bảo hiểm bán kèm',
		'Bảo hiểm độc lập',
	],
	'Lợi ích sản phẩm': [
		'Tận hưởng lợi ích tối đa với các sản phẩm ưu đãi lãi suất 0%',
		'Duyệt vay nhanh chỉ trong 10 phút',
		'Có thể hủy bỏ HĐ vay trong vòng 14 ngày mà không phải trả lãi hay bất kỳ khoản phí nào',
		'Mạng lưới trải rộng khắp toàn quốc',
		'Tra cứu khoản vay nhanh chóng bằng ứng dụng Home Credit trên điện thoại',
		'Không cần thế chấp hoặc chứng minh thu nhập',
		'Đa dạng về lãi suất',
		'Đa dạng về kỳ hạn',
		'Đa dạng về khoản trả trước',
		'Thủ tục đơn giản, chỉ cần CMND, CCCD là có thể làm được HĐ',
	],
	'Công cụ hỗ trợ': [
		'Ứng dụng HomeX',
		'Ứng dụng học trực tuyến Go Learn',
		'Ứng dụng của Home Credit - GMA',
	],
	'Giới thiệu ứng dụng': [
		'Là ứng dụng công nghệ hỗ trợ bán hàng cho đội ngũ kinh doanh của HCVN, được cài đặt trực tiếp trên điện thoại, được tích hợp nhiều tính năng giúp cho công việc bán hàng thuận tiện và đơn giản hơn',
		'Là ứng dụng học trực tuyến giúp người dùng truy cập nội dung học tập, xem các khóa học và nội dung được chia sẻ mọi lúc, mọi nơi, có thể làm bài kiểm tra trực tiếp trên ứng dụng',
		'Là ứng dụng giúp KH quản lý hợp đồng vay, theo dõi lịch thanh toán và hỗ trợ giải đáp tư vấn 24/7, thanh toán mọi giao dịch, hóa đơn dễ dàng, chơi game và mang về những phần quà hấp dẫn',
	],
	'Minh họa ứng dụng': [
		'569821ef-9f90-4780-95d0-11a7fe034c45_e0ee307cdedb454598bd817902c717de.png',
		'569821ef-9f90-4780-95d0-11a7fe034c45_f73c3caa467e4cf0942fb369a86cd37f.png',
		'569821ef-9f90-4780-95d0-11a7fe034c45_af2f00d1c3ad49ab80884ef40f52402c.jpg',
	],
	'Thuật ngữ sản phẩm': [
		'Khoản trả trước',
		'Khoản vay',
		'Thời hạn vay',
		'Lãi suất',
		'Phí bảo hiểm',
		'Số tiền bảo hiểm',
		'Người được bảo hiểm',
		'Người thụ hưởng quyền lợi bảo hiểm',
		'Các giấy tờ yêu cầu',
	],
	'Chi tiết thuật ngữ SP': [
		'Số tiền KH có thể trả trước khi tham gia vay, được tính theo % trên giá sản phẩm',
		'Số tiền còn lại sau khi KH thanh toán khoản trả trước, chưa bao gồm phí bảo hiểm',
		'Số tháng KH hoàn tất khoản vay theo hợp đồng tín dụng',
		'Tỷ lệ % tiền lãi mà KH vay có trách nhiệm trả cho việc thực hiện trả góp, tính lãi suất trên dư nợ giảm dần',
		'Khoản tiền mà người tham gia bảo hiểm trả cho doanh nghiệp bảo hiểm, để đổi lấy việc doanh nghiệp bảo hiểm bồi thường hoặc trả tiền bảo hiểm như đã cam kết trong HĐ bảo hiểm',
		'Số tiền tối đa mà doanh nghiệp bảo hiểm có thể phải trả khi phát sinh sự kiện bảo hiểm hoặc là mức trách nhiệm tối đa của doanh nghiệp bảo hiểm theo một HĐ bồi thường, được ghi rõ trong HĐ bảo hiểm',
		'Thỏa thuận bằng văn bản giữa công ty Bảo hiểm và Bên mua bảo hiểm quy định các quyền lợi và nghĩa vụ của Người được bảo hiểm, công ty bảo hiểm và Người thụ hưởng|Bao gồm điều khoản bảo hiểm, giấy yêu cầu bảo hiểm, đơn bảo hiểm, HĐ bảo hiểm, các điều khoản bảo hiểm sửa đổi nếu có và các thỏa thuận khác đã được lập thành văn bản giữa các bên|Do Công Ty Tài Chính TNHH Một Thanh Viên Home Credit Việt Nam thau mặt Công ty bảo hiểm cấp cho KH',
		'Người được hưởng số tiền mà doanh nghiệp bảo hiểm bồi thường hoặc chi trả khi xảy ra sự kiện bảo hiểm',
		'Các loại giấy tờ tuỳ thân mà KH có thể cung cấp, bao gồm CMND, CCCD hoặc giấy tờ khác theo yêu cầu của khoản vay',
	],
	'Tên sản phẩm': [
		'Vay trả góp xe máy - TW',
		'Vay trả góp kim khí điện máy - CD',
		'Gói bảo vệ toàn diện thiết bị di động - ADLD',
		'Bảo vệ xe máy toàn diện - TWI',
		'Bảo hiểm trang thiết bị trong nhà - HOCO',
		'Sức khoẻ nội trú - ITP',
		'Bảo hiểm tai nạn - PA',
		'Bảo vệ sức khoẻ toàn diện - CHP',
		'An tâm tài chính - PPI',
		'Tiền mặt bán chéo - CLX',
		'Thẻ tín dụng CCX',
		'Thẻ tín dụng VCC',
		'Tiền mặt trực tuyến - ACL',
	],
	'Mô tả sản phẩm': [
		'Cho vay để khách hàng mua xe máy',
		'Cho vay để mua điện thoại, laptop, máy tính bảng, v.v',
		'Hỗ trợ KH trong trường hợp các thiết bị công nghệ như laptop, điện thoại, máy tính bảng bị rơi vỡ màn hình hoặc rơi vào chất lỏng',
		'Giúp KH an tâm hơn trong quá trình sử dụng xe nếu chẳng may bị tai nạn, mất cắp',
		'Bảo vệ cho các thiết bị trong nhà của KH trong 1 số trường hợp rủi ro xảy ra',
		'Dành cho KH nhập viện điều trị do bị bệnh',
		'Dành cho KH điều trị do bị tai nạn',
		'Dành cho KH điều trị do bị bệnh, bị tai nạn',
		'Hỗ trợ KH nếu không may vợ, chồng hợp pháp của KH không may xảy ra tai nạn, dẫn tới không thể thanh toán khoản vay cho Home Credit được nữa',
		'Cho vay tiền mặt, dành cho những KH đã từng vay mua hàng trả góp tại Home Credit',
		'Thẻ tín dụng vật lý',
		'Thẻ tín dụng trực tuyến',
		'Cho vay tiền mặt trực tuyến dành cho KH chưa từng có giao dịch vay trả góp với Home Credit, hoặc KH đã từng có giao dịch vay trả góp với Home Credit nhưng không được đề xuất vay gói CLX',
	],
	'Vai trò, trách nhiệm của SA': [
		'Sơ đồ tổ chức phòng Sales',
		'Vai trò của SA',
		'Trách nhiệm của SA',
		'Những việc làm hàng ngày của SA',
		'Quyền lợi của SA',
		'Tác phong',
		'Xây dựng mối quan hệ với cửa hàng',
	],
	'Chi tiết SA': [
		'SA trực thuộc mạng lưới kinh doanh (MLKD) và báo cáo trực tiếp cho quản lý kinh doanh khu vực (DSM)',
		'Là người trực tiếp mang nguồn thu nhập, lợi nhuận về cho công ty, đảm bảo mục tiêu kinh doanh với tỷ lệ rủi ro thấp nhất|Là đại sứ thương hiệu công ty, là chuyên gia tư vấn tài chính giúp KH có được những sản phẩm tài chính uy tín, chất lượng, dịch vụ tận tâm và phù hợp với nhu cầu|Là người đồng hành, xây dựng mối quan hệ tốt đẹp với đối tác và luôn chia sẻ, hỗ trợ với tinh thần win – win',
		'Tìm kiếm, tiếp cận, tư vấn các khoản vay đến KH với chất lượng dịch vụ chuyên nghiệp|Xây dựng mối quan hệ với các cửa hàng đối tác|Kiểm soát rủi ro gian lận|Tuân thủ các quy trình, quy định và chỉ thị từ cấp trên, công ty|Kiểm soát nợ xấu bằng cách nhận diện KH gian lận, kiểm tra chứng từ và theo dõi tình trạng đóng phí của KH',
		'Được DSM phân công làm 2 ca 1 ngày|Sắp xếp thời gian hợp lý, phân chia công việc một cách rõ ràng và tận dụng tối đa một ngày làm việc|Ưu tiên nhất việc tìm kiếm và tiếp cận KH vì ảnh hưởng trực tiếp đến thu nhập|Tìm kiếm KH qua các kênh khác nhau (Hệ thống HomeX, Gọi điện thoại, Đăng bài Facebook,...)|Tiếp cận và tư vấn sản phẩm cho khách hàng|Thực hiện hợp đồng|Hỗ trợ các cửa hàng khác khi có yêu cầu từ quản lý|Gặp gỡ KH ở bên ngoài (quán cafe, nhà của KH) khi cần thiết|Làm việc tại shop bán xe máy hoặc cửa hàng bán điện thoại, đồ điện máy',
		'Thu nhập thực nhận bằng Tổng thu nhập gộp trừ đi Các khoản khấu trừ|Có cơ hội phát triển theo định hướng Người bán hàng chuyên nghiệp|Có cơ hội phát triển theo định hướng Nhà quản lý kinh doanh khu vực|Có cơ hội học tập bằng các khóa học trên E-learning, Workshop, Talkshow,...',
	],
	'Ứng xử với CH': [
		'Thông báo lịch làm việc cho quản lý cửa hàng',
		'Tuân thủ quy định, giờ giấc của cửa hàng',
		'Hợp tác, hỗ trợ, tạo niềm tin & duy trì mối quan hệ tốt với cửa hàng',
		'Hỗ trợ việc tư vấn sản phẩm của cửa hàng',
		'Tìm hiểu đặc điểm & quyền lợi sản phẩm của cửa hàng',
		'Hướng dẫn KH làm thủ tục thanh toán, bảo trì, cũng như giải đáp một số câu hỏi của KH trong những lúc cao điểm',
		'Tùy tiện đến làm việc hoặc rời khỏi cửa hàng mà không thông báo quản lý',
		'Đi làm trễ, về sớm so với quy định',
		'Để mất lòng tin với cửa hàng',
		'Chỉ tư vấn khách hàng có nhu cầu với sản phẩm của Home Credit',
		'Chỉ nắm rõ đặc điểm & quyền lợi sản phẩm của Home Credit',
		'Xem việc hướng dẫn khách hàng thủ tục thanh toán, phương thức bảo trì là nhiệm vụ của nhân viên cửa hàng',
	],
	'Tiêu chí lên cấp bậc': [
		'Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 320 triệu VND',
		'Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 600 triệu VND',
		'Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 900 triệu VND',
		'Trong tháng tính thưởng, không vi phạm dẫn đến nhận bất kỳ Soft Trigger (điểm bắt lỗi cảnh cáo)',
		'Trong tháng tính thưởng, không vi phạm dẫn đến nhận bất kỳ Thẻ vàng (thư cảnh cáo)',
		'Trong tháng tính thưởng, không vi phạm dẫn đến nhận bất kỳ 02 Thư khiển trách trở lên',
		'Trong 2 tháng liên tiếp, đậu tất cả các bài kiểm tra được giao trên E-Learning',
		'Không tham gia lớp tái huấn luyện trong 02 tháng liên tiếp, vì có tỷ lệ lỗi hợp đồng trên tổng số hợp đồng đã ký hơn 10%',
		'Không tham gia lớp tái huấn luyện trong 02 tháng liên tiếp, vì phạm trên 05 lỗi, và/hoặc bị nhận thư khiển trách',
		'Không tham gia lớp tái huấn luyện trong 02 tháng liên tiếp, vì bị phạt thẻ vàng',
		'Làm việc tại Home Credit với chức vụ SA ít nhất 03 tháng',
		'Làm việc tại Home Credit với chức vụ SA ít nhất 06 tháng',
		'Không yêu cầu lịch sử cấp bậc',
		'Trong vòng 1 năm (không tính thời gian nghỉ thai sản), có tối thiểu 03 tháng (không cần liên tiếp) ở vị trí SSA hoặc cấp bậc cao hơn',
		'Thâm niên từ 1 năm trở lên',
		'Kết quả kinh doanh trong 6 tháng gần nhất lớn hơn TB hiệu suất của SA trong cùng 1 tỉnh',
		'Tham gia đầy đủ và vượt qua tất cả các khóa học, bài thi E-Learning xét trong 3 tháng gần nhất',
		'Vượt qua kỳ sát hạch đánh giá năng lực phát triển thông qua tình huống (ADC)',
		'Đạt phỏng vấn với Quản lý mạng lưới kinh doanh toàn quốc hoặc người được ủy quyền',
		'Tốt nghiệp chương trình huấn luyện Quản Lý Kinh Doanh Khu Vực',
	],
	'Các mục tiêu doanh số': [
		'Tổng doanh số tháng từ 150 triệu của các sản phẩm CD, TW, CLX ở bước Ký',
		'Tổng doanh số tháng từ 225 triệu của các sản phẩm CD, TW, CLX ở bước Ký',
		'Tổng doanh số tháng từ 300 triệu của các sản phẩm CD, TW, CLX ở bước Ký',
		'Tổng doanh số CD và TW ở bước Ký từ 20 triệu',
		'Doanh số LCX ở bước Ký từ 30 triệu (trừ Proactive, Online)',
		'Từ 03 HĐ bảo hiểm PPI hoặc TWI Combo ở bước Ký (trừ Proactive, Online)',
		'Từ 02 HĐ bảo hiểm độc lập ở bước Ký',
		'Từ 03 apply sản phẩm CL (gồm CLX, ACL)',
		'Tổng doanh số CD và TW ở bước Ký từ 30 triệu',
		'Doanh số LCX ở bước Ký từ 45 triệu (trừ Proactive, Online)',
		'Từ 04 HĐ bảo hiểm PPI hoặc TWI Combo ở bước Ký (trừ Proactive, Online)',
		'Từ 03 HĐ bảo hiểm độc lập ở bước Ký',
		'Từ 05 apply sản phẩm CL (gồm CLX, ACL)',
		'Tổng doanh số CD và TW ở bước Ký từ 40 triệu',
		'Doanh số LCX ở bước Ký từ 60 triệu (trừ Proactive, Online)',
		'Từ 06 apply sản phẩm CL (gồm CLX, ACL) và 1 apply Card',
		'Từ 05 HĐ bảo hiểm PPI hoặc TWI Combo ở bước Ký (trừ Proactive, Online)',
		'Từ 04 HĐ bảo hiểm độc lập ở bước Ký',
		'Từ 02 thẻ tín dụng phát hành mới ở bước Ký và tỷ lệ số thẻ phát hành tháng liền trước được sử dụng từ 30%',
	],
	'Các cấp độ của SA': [
		'SA',
		'Senior SA (SSA)',
		'Master SA (MSA)',
		'Warrior SA (WSA)',
		'DSM',
		'ASM',
		'RSM',
	],
	'Thâm niên SA': [
		'Dưới 1 năm',
		'Từ 1- 5 năm',
		'Trên 5 năm',
		'Dưới 2 tháng',
		'Từ 2 - 4 tháng',
		'Từ 4 tháng trở lên',
	],
	'Hệ số thâm niên': [
		'1.0',
		'1.2',
		'1.5',
	],
	'Các khoản thu nhập và khấu trừ': [
		'Lương ngoài giờ',
		'Phụ cấp theo kết quả công việc, lương tháng 13',
		'Thưởng cấp bậc',
		'Phụ cấp, trợ cấp',
		'Bảo hiểm bắt buộc',
	],
	'Thuộc tính khoản thu nhập, khấu trừ': [
		'Chỉ làm ngoài giờ theo yêu cầu của cấp trên|Làm việc không quá: 200 giờ 1 năm, 4 giờ 1 ngày làm việc, 30 giờ 1 tháng|Sau khi làm việc, nhân viên sẽ được ưu tiên sắp xếp nghỉ bù, nếu không, số giờ làm thêm được quy thành tiền theo tỷ lệ|Lương ngoài giờ chưa bao gồm 100% lương ngày công hoặc theo chế độ phụ cấp công việc của từng phòng ban',
		'Phụ cấp/trợ cấp theo kết quả công việc được tính theo theo chính sách của công ty|Tùy thuộc vào kết quả kinh doanh của công ty, nhân viên có thể nhận được lương tháng 13|Nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 sẽ được tính theo tỷ lệ',
		'Có 4 cấp độ dành cho nhân viên bán hàng tương ứng với các mức thưởng|SA vẫn được giữ nguyên chức vụ trong suốt thời gian nghỉ thai sản nhưng sẽ không được nhận khoản tiền này|Khoản tiền này sẽ bắt đầu được tính khi SA quay trở lại làm việc sau thời kỳ nghỉ thai sản miễn là phải đáp ứng các tiêu chí theo qui định|Kết quả trung bình của 02 tháng trong tháng đầu tiên sau khi SA quay trở lại làm việc bằng tháng đầu tiên sau khi quay trở lại và 01 tháng trước nghỉ thai sản|Trong trường hợp SA không duy trì được tiêu chí cấp bậc hoặc bị đánh lỗi soft trigger, nhận thẻ vàng, 2 thư khiển trách trở lên, SA sẽ bị giáng cấp và mất khoản tiền này|Tháng tính thưởng bằng Tháng thưởng cộng 1',
	],
	'Công thức tính': [
		'Bằng 150% lương ngày công khi làm việc ngoài giờ trong ngày làm việc bình thường|Bằng 200% lương ngày công khi làm việc ngoài giờ trong ngày nghỉ tuần|Bằng 300% lương ngày công (trong đó 100% đã bao gồm trong tiền lương ngày lễ, tết) khi làm việc ngoài giờ trong ngày lễ, tết',
		'Được tính theo chính sách của công ty, nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 được tính theo tỷ lệ',
		'Doanh số tính cho SA thực hiện Bước 2 đối với CD, TW, CLX|Doanh số tính cho SA thực hiện Bước 1 và Bước 2 đối với ACL (trong trường hợp 1 SA cùng thực hiện cả Bước 1 và Bước 2 thì chỉ tính 1 lần)|Doanh số tính cho SA tạo hợp đồng đối với sản phẩm S.A.I|Doanh số tính cho SA thực hiện Bước 1 đối với sản phẩm Thẻ|Khoản cộng A trong công thức tính doanh số bằng Tổng khoản vay bao gồm phí bảo hiểm của CD, TW, CLX, ACL, S.A.I ký trong tháng thưởng cộng Số thẻ tín dụng được ký trong 1 tháng liền trước có phát sinh giao dịch trong tháng thưởng nhân 40 triệu VND|Khoản trừ B trong công thức tính doanh số bằng Tổng khoản vay bao gồm phí bảo hiểm của CD, TW, CLX, ACL, S.A.I bị hủy trong tháng thưởng cộng Số thẻ tín dụng đã được thưởng trong 1 tháng liền trước nhưng bị đóng trong tháng thưởng nhân 40 triệu VND|Doanh số bằng Khoản cộng A trừ Khoản trừ B theo quy định',
	],
	'Loại quyền lợi': [
		'Tổng thu nhập gộp',
		'Các khoản khấu trừ',
		'Cơ hội phát triển theo định hướng Người bán hàng chuyên nghiệp',
		'Cơ hội phát triển theo định hướng Nhà quản lý kinh doanh khu vực',
		'Cơ hội học tập bằng các khóa học trên E-learning, Workshop, Talkshow,...',
		'Thu nhập thực nhận',
	],
	'Chân dung KH': [
		'Có hợp đồng lao động',
		'Thu nhập ổn định',
		'Chứng minh được tài chính, thu nhập',
		'Có tài sản thế chấp',
		'Vay số tiền lớn',
		'Từ công nhân đến người kinh doanh, sinh viên còn đi học hoặc đã tốt nghiệp, người lao động phổ thông',
		'Người dưới chuẩn cấp tín dụng của ngân hàng',
		'Người cần sản phẩm, số tiền mặt nhỏ để phục vụ nhu cầu tiêu dùng',
		'Độ tuổi từ 20 - 61 tuổi',
		'Công dân Việt Nam cư trú trên lãnh thổ Việt Nam',
		'Đủ năng lực hành vi dân sự (biết đọc, viết, hoàn toàn tỉnh táo tại thời điểm thực hiện hồ sơ vay)',
	],
	'Chân dung khách hàng': [
		'Khách hàng 1',
		'Khách hàng 2',
		'Khách hàng 3',
		'Khách hàng 4',
		'Khách hàng 5',
	],
	'Điều kiện xác định nhóm nợ': [
		'Có khả năng trả nợ cao nhất, khi khoản nợ của các nhóm này đều chưa đến hạn thanh toán',
		'Điều kiện kinh tế của các bên nợ được đánh giá là có khả năng thu hồi đầy đủ cả gốc và lãi',
		'Đã chậm thanh toán khoản nợ đến 90 ngày theo nội dung hợp đồng tín dụng',
		'Có một số khoản nợ thuộc nhóm nợ cao hơn, hoặc thấp hơn nhưng đáp ứng điều kiện: Bên vay đã trả đầy đủ phần nợ gốc và lãi quá hạn và nợ gốc và lãi của các kỳ hạn trả nợ tiếp theo kể từ ngày bắt đầu trả đầy đủ nợ gốc và lãi bị quá hạn',
		'Có một số khoản nợ thuộc nhóm nợ cao hơn, hoặc thấp hơn nhưng đáp ứng điều kiện: có đầy đủ tài liệu, hồ sơ chứng minh bên nợ đã trả nợ',
		'Có một số khoản nợ thuộc nhóm nợ cao hơn, hoặc thấp hơn nhưng đáp ứng điều kiện: Tổ chức tín dụng, chi nhánh ngân hàng nước ngoài có đủ cơ sở thông tin, tài liệu đánh giá khách hàng có khả năng trả đầy đủ nợ gốc và lãi còn lại đúng thời hạn',
		'Đã chậm thanh toán khoản nợ từ 91 ngày đến 180 ngày, và khoản nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ nhưng khoản nợ được gia hạn lần đầu vẫn còn trong hạn',
		'Có độ tín nhiệm rất thấp khi đã quá hạn trả nợ từ 181 ngày đến 360 ngày, bên nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ lần đầu, tuy nhiên tiếp tục quá hạn trả nợ đến 90 ngày đối với thời gian trả nợ đã được cơ cấu lần đầu',
		'Được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ lần 2 nhưng vẫn chưa quá hạn',
		'Có một số khoản nợ phải thu hồi theo kết luận thanh tra, kiểm tra nhưng quá thời hạn thu hồi theo kết luận thanh tra, kiểm tra đến 60 ngày mà chưa thu hồi được',
		'Có khoản nợ phải thu hồi theo quyết định thu hồi nợ trước hạn của tổ chức tín dụng, chi nhánh ngân hàng nước ngoài do KH vi phạm thỏa thuận với tổ chức tín dụng, chi nhánh ngân hàng nước ngoài chưa thu hồi được trong thời gian từ 30 ngày đến 60 ngày kể từ ngày có quyết định thu hồi',
		'Có khả năng thu hồi nợ rất thấp, khoản nợ đã quá hạn trên 360 ngày, khoản nợ cơ cấu lại thời hạn trả nợ lần đầu quá hạn từ 91 ngày trở lên theo thời hạn trả nợ được cơ cấu lại lần đầu',
		'Có khoản nợ cơ cấu lại thời hạn trả nợ lần thứ hai nhưng tiếp tục quá hạn theo thời hạn trả nợ được cơ cấu lại lần thứ hai',
		'Có khoản nợ được cơ cấu lại thời hạn trả nợ lần thứ ba trở lên',
		'Có một số khoản nợ phải thu hồi theo kết luận thanh tra, kiểm tra nhưng quá thời hạn thu hồi theo kết luận thanh tra, kiểm tra trên 60 ngày mà chưa thu hồi được',
		'Có khoản nợ phải thu hồi theo quyết định thu hồi nợ trước hạn của tổ chức tín dụng, chi nhánh ngân hàng nước ngoài do khách hàng vi phạm thỏa thuận với tổ chức tín dụng, chi nhánh ngân hàng nước ngoài chưa thu hồi được trên 60 ngày kể từ ngày có quyết định thu hồi',
		'Có thể thuộc trường hợp được miễn hoặc giảm lãi do KH không đủ khả năng trả lãi đầy đủ theo thỏa thuận',
		'Không được miễn hoặc giảm lãi khi bên nợ không cung cấp đầy đủ, kịp thời và trung thực các thông tin theo yêu cầu của tổ chức tín dụng, chi nhánh ngân hàng, chi nhánh ngân hàng nước ngoài để đánh giá khả năng trả nợ',
		'Không được miễn hoặc giảm lãi khi khoản nợ mà hành vi cấp tín dụng bị xử phạt vi phạm hành chính theo quy định của pháp luật',
		'Không được miễn hoặc giảm lãi khi các chỉ tiêu về khả năng sinh lời, khả năng thanh toán, tỷ lệ nợ trên vốn, dòng tiền, khả năng trả nợ của KH suy giảm liên tục qua 03 lần đánh giá, phân loại nợ liên tục',
		'Thanh toán quá hạn dưới 10 ngày, nhưng được đánh giá là có khả năng thu hồi đầy đủ cả lãi quá hạn và nợ gốc',
	],
	'Nhóm nợ': [
		'Nhóm nợ 1: Nợ đủ tiêu chuẩn',
		'Nhóm nợ 2: Nợ cần chú ý',
		'Nhóm nợ 3: Nợ dưới tiêu chuẩn',
		'Nhóm nợ 4: Nợ nghi ngờ',
		'Nhóm nợ 5: Nợ có khả năng mất vốn',
	],
	'Mức trích lập dự phòng chung': [
		'0,75% tổng số dư các khoản nợ từ nhóm 1 đến nhóm 4',
		'Tiền gửi tại tổ chức tín dụng, chi nhánh ngân hàng nước ngoài theo quy định của pháp luật và tiền gửi tại tổ chức tín dụng ở nước ngoài',
		'Khoản cho vay, mua có kỳ hạn giấy tờ có giá giữa các tổ chức tín dụng, chi nhánh ngân hàng nước ngoài tại Việt Nam',
		'Khoản mua kỳ phiếu, tín phiếu, chứng chỉ tiền gửi, trái phiếu do tổ chức tín dụng, chi nhánh ngân hàng nước ngoài khác phát hành trong nước',
		'Khoản mua bán lại trái phiếu Chính phủ theo quy định tại điểm l khoản 1 Điều 1 Thông tư này',
	],
	'Đánh giá tác phong': [
		'nên',
		'không nên',
	],
	'Đánh giá ứng xử': [
		'NÊN',
		'KHÔNG NÊN',
	],
	'Số tiền thưởng cấp bậc': [
		'600.000 đồng một tháng',
		'720.000 đồng một tháng',
		'900.000 đồng một tháng',
		'1.800.000 đồng một tháng',
		'2.160.000 đồng một tháng',
		'2.700.000 đồng một tháng',
		'3.600.000 đồng một tháng',
		'4.320.000 đồng một tháng',
		'5.400.000 đồng một tháng',
	],
}