knowledge_graph = {
	('Tổng quan về công ty', 'Chi tiết công ty'): {
		'Sứ mệnh': ('Mang lại những dịch vụ tài chính đáng tin cậy tới cho khách hàng và đối tác để tiếp cận thông qua các kênh tùy chọn|Liên tục đáp ứng những nhu cầu mới, dù là trực tiếp hay qua những hệ sinh thái đột phá, góp phần xây dựng một thế giới vững mạnh hơn',),
		'Quy mô phát tiển tại Việt Nam': ('Là một trong những công ty hàng đầu trong lĩnh vực tài chính tiêu dùng, hiện có trụ sở chính tại TP.HCM và văn phòng đại diện tại 10 tỉnh thành trên toàn quốc|Mạng lưới 9.000 điểm bán lẻ tại 63 tỉnh thành trên toàn quốc, phục vụ hơn 13 triệu khách hàng, đã có 8,3 triệu lượt tải ứng dụng Home Credit trên điện thoại',),
		'Cột mốc phát triển': ('Được cấp giấy phép vào năm 2008, đến năm 2009 công ty chính thức ra mắt thương hiệu và triển khai sản phẩm đầu tiên|Cuối năm 2022, đẩy mạnh phát triển theo hướng số hóa, ra mắt ứng dụng trên điện thoại giúp KH có thể thực hiện và theo dõi khoản vay trực tuyến dễ dàng',),
		'Lịch sử thành lập': ('Tập đoàn Home Credit được thành lập năm 1997 ở Cộng Hòa Czech. Cho đến nay, Home Credit đã trở thành một trong những tập đoàn hàng đầu thế giới về lĩnh vực cho vay tài chính tiêu dùng|Hiện nay Home Credit đang phục vụ cho hơn 141 triệu khách hàng; hơn 98 triệu người dùng ứng dụng với gần 42 ngàn hợp đồng được tạo mới mỗi ngày|Những quốc gia, vùng lãnh thổ đã có sự xuất hiện của Home Credit trên 10 năm là: Philipine, Indonesia, India, China, Việt Nam',),
		'Tầm nhìn': ('Giúp khách hàng làm chủ cuộc sống và sống vui như mong đợi',),
		'Khách hàng của ngân hàng': ('nan',),
		'Thành tựu nổi bật': ('Giải thưởng top 100 công ty có môi trường làm việc tốt nhất khu vực châu Á – Thái Bình Dương năm 2021|Giải thưởng Golden Dragon Awards 2021 dành cho doanh nghiệp tiên phong đổi mới, sáng tạo, ứng dụng công nghệ vào quy trình kinh doanh và quản trị doanh nghiệp|Giải thưởng doanh nghiệp Bắc Âu 2021 dành cho doanh nghiệp FDI có những sáng kiến, hỗ trợ và đóng góp tích cực trong đại dịch Covid-19 tại Việt Nam|Giải thưởng Inspirational Brand Award – Thương hiệu truyền cảm hứng, chỉ dành riêng cho những doanh nghiệp có thương hiệu sản phẩm dịch vụ truyền cảm hứng hoặc ảnh hưởng tích cực tới cộng đồng và được người tiêu dùng, công chúng tin tưởng lựa chọn, ủng hộ|Giải thưởng Visa Awards 2021 – của tổ chức Visa toàn cầu trao tặng cho doanh nghiệp có những đổi mới sáng tạo, tăng trưởng năng động và dịch vụ tốt nhất trong phân khúc|Giải thưởng The Global Economics Awards 2021 dành cho doanh nghiệp có đóng góp những thành tựu to lớn trong các lĩnh vực Ngân hàng, Tài chính, Bất động sản, Bảo hiểm, Năng lượng và Công nghệ',),
		'Đối tác': ('Hợp tác với gần 13.000 cửa hàng bán lẻ xe máy, điện thoại di động, cửa hàng điện tử và các nhà sản xuất trên toàn quốc với các thương hiệu nổi tiếng như: Thế Giới Di Động, Samsung, Yamaha,…',),
		'Khách hàng đủ điều kiện làm hợp đồng với Home Credit': ('nan',),
	},
	('Chi tiết công ty', 'Tổng quan về công ty'): {
		'Mang lại những dịch vụ tài chính đáng tin cậy tới cho khách hàng và đối tác để tiếp cận thông qua các kênh tùy chọn|Liên tục đáp ứng những nhu cầu mới, dù là trực tiếp hay qua những hệ sinh thái đột phá, góp phần xây dựng một thế giới vững mạnh hơn': ('Sứ mệnh',),
		'Là một trong những công ty hàng đầu trong lĩnh vực tài chính tiêu dùng, hiện có trụ sở chính tại TP.HCM và văn phòng đại diện tại 10 tỉnh thành trên toàn quốc|Mạng lưới 9.000 điểm bán lẻ tại 63 tỉnh thành trên toàn quốc, phục vụ hơn 13 triệu khách hàng, đã có 8,3 triệu lượt tải ứng dụng Home Credit trên điện thoại': ('Quy mô phát tiển tại Việt Nam',),
		'Được cấp giấy phép vào năm 2008, đến năm 2009 công ty chính thức ra mắt thương hiệu và triển khai sản phẩm đầu tiên|Cuối năm 2022, đẩy mạnh phát triển theo hướng số hóa, ra mắt ứng dụng trên điện thoại giúp KH có thể thực hiện và theo dõi khoản vay trực tuyến dễ dàng': ('Cột mốc phát triển',),
		'Tập đoàn Home Credit được thành lập năm 1997 ở Cộng Hòa Czech. Cho đến nay, Home Credit đã trở thành một trong những tập đoàn hàng đầu thế giới về lĩnh vực cho vay tài chính tiêu dùng|Hiện nay Home Credit đang phục vụ cho hơn 141 triệu khách hàng; hơn 98 triệu người dùng ứng dụng với gần 42 ngàn hợp đồng được tạo mới mỗi ngày|Những quốc gia, vùng lãnh thổ đã có sự xuất hiện của Home Credit trên 10 năm là: Philipine, Indonesia, India, China, Việt Nam': ('Lịch sử thành lập',),
		'Giúp khách hàng làm chủ cuộc sống và sống vui như mong đợi': ('Tầm nhìn',),
		'nan': ('Khách hàng đủ điều kiện làm hợp đồng với Home Credit',),
		'Giải thưởng top 100 công ty có môi trường làm việc tốt nhất khu vực châu Á – Thái Bình Dương năm 2021|Giải thưởng Golden Dragon Awards 2021 dành cho doanh nghiệp tiên phong đổi mới, sáng tạo, ứng dụng công nghệ vào quy trình kinh doanh và quản trị doanh nghiệp|Giải thưởng doanh nghiệp Bắc Âu 2021 dành cho doanh nghiệp FDI có những sáng kiến, hỗ trợ và đóng góp tích cực trong đại dịch Covid-19 tại Việt Nam|Giải thưởng Inspirational Brand Award – Thương hiệu truyền cảm hứng, chỉ dành riêng cho những doanh nghiệp có thương hiệu sản phẩm dịch vụ truyền cảm hứng hoặc ảnh hưởng tích cực tới cộng đồng và được người tiêu dùng, công chúng tin tưởng lựa chọn, ủng hộ|Giải thưởng Visa Awards 2021 – của tổ chức Visa toàn cầu trao tặng cho doanh nghiệp có những đổi mới sáng tạo, tăng trưởng năng động và dịch vụ tốt nhất trong phân khúc|Giải thưởng The Global Economics Awards 2021 dành cho doanh nghiệp có đóng góp những thành tựu to lớn trong các lĩnh vực Ngân hàng, Tài chính, Bất động sản, Bảo hiểm, Năng lượng và Công nghệ': ('Thành tựu nổi bật',),
		'Hợp tác với gần 13.000 cửa hàng bán lẻ xe máy, điện thoại di động, cửa hàng điện tử và các nhà sản xuất trên toàn quốc với các thương hiệu nổi tiếng như: Thế Giới Di Động, Samsung, Yamaha,…': ('Đối tác',),
	},
	('Công cụ hỗ trợ', 'Giới thiệu ứng dụng', 'Minh họa ứng dụng'): {
		'Ứng dụng HomeX': ('Là ứng dụng công nghệ hỗ trợ bán hàng cho đội ngũ kinh doanh của HCVN, được cài đặt trực tiếp trên điện thoại, được tích hợp nhiều tính năng giúp cho công việc bán hàng thuận tiện và đơn giản hơn', '569821ef-9f90-4780-95d0-11a7fe034c45_e0ee307cdedb454598bd817902c717de.png'),
		'Ứng dụng học trực tuyến Go Learn': ('Là ứng dụng học trực tuyến giúp người dùng truy cập nội dung học tập, xem các khóa học và nội dung được chia sẻ mọi lúc, mọi nơi, có thể làm bài kiểm tra trực tiếp trên ứng dụng', '569821ef-9f90-4780-95d0-11a7fe034c45_f73c3caa467e4cf0942fb369a86cd37f.png'),
		'Ứng dụng của Home Credit - GMA': ('Là ứng dụng giúp KH quản lý hợp đồng vay, theo dõi lịch thanh toán và hỗ trợ giải đáp tư vấn 24/7, thanh toán mọi giao dịch, hóa đơn dễ dàng, chơi game và mang về những phần quà hấp dẫn', '569821ef-9f90-4780-95d0-11a7fe034c45_af2f00d1c3ad49ab80884ef40f52402c.jpg'),
	},
	('Giới thiệu ứng dụng', 'Công cụ hỗ trợ', 'Minh họa ứng dụng'): {
		'Là ứng dụng công nghệ hỗ trợ bán hàng cho đội ngũ kinh doanh của HCVN, được cài đặt trực tiếp trên điện thoại, được tích hợp nhiều tính năng giúp cho công việc bán hàng thuận tiện và đơn giản hơn': ('Ứng dụng HomeX', '569821ef-9f90-4780-95d0-11a7fe034c45_e0ee307cdedb454598bd817902c717de.png'),
		'Là ứng dụng học trực tuyến giúp người dùng truy cập nội dung học tập, xem các khóa học và nội dung được chia sẻ mọi lúc, mọi nơi, có thể làm bài kiểm tra trực tiếp trên ứng dụng': ('Ứng dụng học trực tuyến Go Learn', '569821ef-9f90-4780-95d0-11a7fe034c45_f73c3caa467e4cf0942fb369a86cd37f.png'),
		'Là ứng dụng giúp KH quản lý hợp đồng vay, theo dõi lịch thanh toán và hỗ trợ giải đáp tư vấn 24/7, thanh toán mọi giao dịch, hóa đơn dễ dàng, chơi game và mang về những phần quà hấp dẫn': ('Ứng dụng của Home Credit - GMA', '569821ef-9f90-4780-95d0-11a7fe034c45_af2f00d1c3ad49ab80884ef40f52402c.jpg'),
	},
	('Minh họa ứng dụng', 'Công cụ hỗ trợ', 'Giới thiệu ứng dụng'): {
		'569821ef-9f90-4780-95d0-11a7fe034c45_e0ee307cdedb454598bd817902c717de.png': ('Ứng dụng HomeX', 'Là ứng dụng công nghệ hỗ trợ bán hàng cho đội ngũ kinh doanh của HCVN, được cài đặt trực tiếp trên điện thoại, được tích hợp nhiều tính năng giúp cho công việc bán hàng thuận tiện và đơn giản hơn'),
		'569821ef-9f90-4780-95d0-11a7fe034c45_f73c3caa467e4cf0942fb369a86cd37f.png': ('Ứng dụng học trực tuyến Go Learn', 'Là ứng dụng học trực tuyến giúp người dùng truy cập nội dung học tập, xem các khóa học và nội dung được chia sẻ mọi lúc, mọi nơi, có thể làm bài kiểm tra trực tiếp trên ứng dụng'),
		'569821ef-9f90-4780-95d0-11a7fe034c45_af2f00d1c3ad49ab80884ef40f52402c.jpg': ('Ứng dụng của Home Credit - GMA', 'Là ứng dụng giúp KH quản lý hợp đồng vay, theo dõi lịch thanh toán và hỗ trợ giải đáp tư vấn 24/7, thanh toán mọi giao dịch, hóa đơn dễ dàng, chơi game và mang về những phần quà hấp dẫn'),
	},
	('Thuật ngữ sản phẩm', 'Chi tiết thuật ngữ SP'): {
		'Khoản trả trước': ('Số tiền KH có thể trả trước khi tham gia vay, được tính theo % trên giá sản phẩm',),
		'Khoản vay': ('Số tiền còn lại sau khi KH thanh toán khoản trả trước, chưa bao gồm phí bảo hiểm',),
		'Thời hạn vay': ('Số tháng KH hoàn tất khoản vay theo hợp đồng tín dụng',),
		'Lãi suất': ('Tỷ lệ % tiền lãi mà KH vay có trách nhiệm trả cho việc thực hiện trả góp, tính lãi suất trên dư nợ giảm dần',),
		'Phí bảo hiểm': ('Khoản tiền mà người tham gia bảo hiểm trả cho doanh nghiệp bảo hiểm, để đổi lấy việc doanh nghiệp bảo hiểm bồi thường hoặc trả tiền bảo hiểm như đã cam kết trong HĐ bảo hiểm',),
		'Số tiền bảo hiểm': ('Số tiền tối đa mà doanh nghiệp bảo hiểm có thể phải trả khi phát sinh sự kiện bảo hiểm hoặc là mức trách nhiệm tối đa của doanh nghiệp bảo hiểm theo một HĐ bồi thường, được ghi rõ trong HĐ bảo hiểm',),
		'Người được bảo hiểm': ('Thỏa thuận bằng văn bản giữa công ty Bảo hiểm và Bên mua bảo hiểm quy định các quyền lợi và nghĩa vụ của Người được bảo hiểm, công ty bảo hiểm và Người thụ hưởng|Bao gồm điều khoản bảo hiểm, giấy yêu cầu bảo hiểm, đơn bảo hiểm, HĐ bảo hiểm, các điều khoản bảo hiểm sửa đổi nếu có và các thỏa thuận khác đã được lập thành văn bản giữa các bên|Do Công Ty Tài Chính TNHH Một Thanh Viên Home Credit Việt Nam thau mặt Công ty bảo hiểm cấp cho KH',),
		'Người thụ hưởng quyền lợi bảo hiểm': ('Người được hưởng số tiền mà doanh nghiệp bảo hiểm bồi thường hoặc chi trả khi xảy ra sự kiện bảo hiểm',),
		'Các giấy tờ yêu cầu': ('Các loại giấy tờ tuỳ thân mà KH có thể cung cấp, bao gồm CMND, CCCD hoặc giấy tờ khác theo yêu cầu của khoản vay',),
	},
	('Chi tiết thuật ngữ SP', 'Thuật ngữ sản phẩm'): {
		'Số tiền KH có thể trả trước khi tham gia vay, được tính theo % trên giá sản phẩm': ('Khoản trả trước',),
		'Số tiền còn lại sau khi KH thanh toán khoản trả trước, chưa bao gồm phí bảo hiểm': ('Khoản vay',),
		'Số tháng KH hoàn tất khoản vay theo hợp đồng tín dụng': ('Thời hạn vay',),
		'Tỷ lệ % tiền lãi mà KH vay có trách nhiệm trả cho việc thực hiện trả góp, tính lãi suất trên dư nợ giảm dần': ('Lãi suất',),
		'Khoản tiền mà người tham gia bảo hiểm trả cho doanh nghiệp bảo hiểm, để đổi lấy việc doanh nghiệp bảo hiểm bồi thường hoặc trả tiền bảo hiểm như đã cam kết trong HĐ bảo hiểm': ('Phí bảo hiểm',),
		'Số tiền tối đa mà doanh nghiệp bảo hiểm có thể phải trả khi phát sinh sự kiện bảo hiểm hoặc là mức trách nhiệm tối đa của doanh nghiệp bảo hiểm theo một HĐ bồi thường, được ghi rõ trong HĐ bảo hiểm': ('Số tiền bảo hiểm',),
		'Thỏa thuận bằng văn bản giữa công ty Bảo hiểm và Bên mua bảo hiểm quy định các quyền lợi và nghĩa vụ của Người được bảo hiểm, công ty bảo hiểm và Người thụ hưởng|Bao gồm điều khoản bảo hiểm, giấy yêu cầu bảo hiểm, đơn bảo hiểm, HĐ bảo hiểm, các điều khoản bảo hiểm sửa đổi nếu có và các thỏa thuận khác đã được lập thành văn bản giữa các bên|Do Công Ty Tài Chính TNHH Một Thanh Viên Home Credit Việt Nam thau mặt Công ty bảo hiểm cấp cho KH': ('Người được bảo hiểm',),
		'Người được hưởng số tiền mà doanh nghiệp bảo hiểm bồi thường hoặc chi trả khi xảy ra sự kiện bảo hiểm': ('Người thụ hưởng quyền lợi bảo hiểm',),
		'Các loại giấy tờ tuỳ thân mà KH có thể cung cấp, bao gồm CMND, CCCD hoặc giấy tờ khác theo yêu cầu của khoản vay': ('Các giấy tờ yêu cầu',),
	},
	('Tên sản phẩm', 'Mô tả sản phẩm'): {
		'Vay trả góp xe máy - TW': ('Cho vay để khách hàng mua xe máy',),
		'Vay trả góp kim khí điện máy - CD': ('Cho vay để mua điện thoại, laptop, máy tính bảng, v.v',),
		'Gói bảo vệ toàn diện thiết bị di động - ADLD': ('Hỗ trợ KH trong trường hợp các thiết bị công nghệ như laptop, điện thoại, máy tính bảng bị rơi vỡ màn hình hoặc rơi vào chất lỏng',),
		'Bảo vệ xe máy toàn diện - TWI': ('Giúp KH an tâm hơn trong quá trình sử dụng xe nếu chẳng may bị tai nạn, mất cắp',),
		'Bảo hiểm trang thiết bị trong nhà - HOCO': ('Bảo vệ cho các thiết bị trong nhà của KH trong 1 số trường hợp rủi ro xảy ra',),
		'Sức khoẻ nội trú - ITP': ('Dành cho KH nhập viện điều trị do bị bệnh',),
		'Bảo hiểm tai nạn - PA': ('Dành cho KH điều trị do bị tai nạn',),
		'Bảo vệ sức khoẻ toàn diện - CHP': ('Dành cho KH điều trị do bị bệnh, bị tai nạn',),
		'An tâm tài chính - PPI': ('Hỗ trợ KH nếu không may vợ, chồng hợp pháp của KH không may xảy ra tai nạn, dẫn tới không thể thanh toán khoản vay cho Home Credit được nữa',),
		'Tiền mặt bán chéo - CLX': ('Cho vay tiền mặt, dành cho những KH đã từng vay mua hàng trả góp tại Home Credit',),
		'Thẻ tín dụng CCX': ('Thẻ tín dụng vật lý',),
		'Thẻ tín dụng VCC': ('Thẻ tín dụng trực tuyến',),
		'Tiền mặt trực tuyến - ACL': ('Cho vay tiền mặt trực tuyến dành cho KH chưa từng có giao dịch vay trả góp với Home Credit, hoặc KH đã từng có giao dịch vay trả góp với Home Credit nhưng không được đề xuất vay gói CLX',),
	},
	('Mô tả sản phẩm', 'Tên sản phẩm'): {
		'Cho vay để khách hàng mua xe máy': ('Vay trả góp xe máy - TW',),
		'Cho vay để mua điện thoại, laptop, máy tính bảng, v.v': ('Vay trả góp kim khí điện máy - CD',),
		'Hỗ trợ KH trong trường hợp các thiết bị công nghệ như laptop, điện thoại, máy tính bảng bị rơi vỡ màn hình hoặc rơi vào chất lỏng': ('Gói bảo vệ toàn diện thiết bị di động - ADLD',),
		'Giúp KH an tâm hơn trong quá trình sử dụng xe nếu chẳng may bị tai nạn, mất cắp': ('Bảo vệ xe máy toàn diện - TWI',),
		'Bảo vệ cho các thiết bị trong nhà của KH trong 1 số trường hợp rủi ro xảy ra': ('Bảo hiểm trang thiết bị trong nhà - HOCO',),
		'Dành cho KH nhập viện điều trị do bị bệnh': ('Sức khoẻ nội trú - ITP',),
		'Dành cho KH điều trị do bị tai nạn': ('Bảo hiểm tai nạn - PA',),
		'Dành cho KH điều trị do bị bệnh, bị tai nạn': ('Bảo vệ sức khoẻ toàn diện - CHP',),
		'Hỗ trợ KH nếu không may vợ, chồng hợp pháp của KH không may xảy ra tai nạn, dẫn tới không thể thanh toán khoản vay cho Home Credit được nữa': ('An tâm tài chính - PPI',),
		'Cho vay tiền mặt, dành cho những KH đã từng vay mua hàng trả góp tại Home Credit': ('Tiền mặt bán chéo - CLX',),
		'Thẻ tín dụng vật lý': ('Thẻ tín dụng CCX',),
		'Thẻ tín dụng trực tuyến': ('Thẻ tín dụng VCC',),
		'Cho vay tiền mặt trực tuyến dành cho KH chưa từng có giao dịch vay trả góp với Home Credit, hoặc KH đã từng có giao dịch vay trả góp với Home Credit nhưng không được đề xuất vay gói CLX': ('Tiền mặt trực tuyến - ACL',),
	},
	('Vai trò, trách nhiệm của SA', 'Chi tiết SA'): {
		'Tác phong': ('\n',),
		'Sơ đồ tổ chức phòng Sales': ('SA trực thuộc mạng lưới kinh doanh (MLKD) và báo cáo trực tiếp cho quản lý kinh doanh khu vực (DSM)',),
		'Mục tiêu doanh số': ('nan',),
		'Xây dựng mối quan hệ với cửa hàng': ('nan',),
		'Vai trò của SA': ('Là người trực tiếp mang nguồn thu nhập, lợi nhuận về cho công ty, đảm bảo mục tiêu kinh doanh với tỷ lệ rủi ro thấp nhất|Là đại sứ thương hiệu công ty, là chuyên gia tư vấn tài chính giúp KH có được những sản phẩm tài chính uy tín, chất lượng, dịch vụ tận tâm và phù hợp với nhu cầu|Là người đồng hành, xây dựng mối quan hệ tốt đẹp với đối tác và luôn chia sẻ, hỗ trợ với tinh thần win – win',),
		'Trách nhiệm của SA': ('Tìm kiếm, tiếp cận, tư vấn các khoản vay đến KH với chất lượng dịch vụ chuyên nghiệp|Xây dựng mối quan hệ với các cửa hàng đối tác|Kiểm soát rủi ro gian lận|Tuân thủ các quy trình, quy định và chỉ thị từ cấp trên, công ty|Kiểm soát nợ xấu bằng cách nhận diện KH gian lận, kiểm tra chứng từ và theo dõi tình trạng đóng phí của KH',),
		'Những việc làm hàng ngày của SA': ('Được DSM phân công làm 2 ca 1 ngày|Sắp xếp thời gian hợp lý, phân chia công việc một cách rõ ràng và tận dụng tối đa một ngày làm việc|Ưu tiên nhất việc tìm kiếm và tiếp cận KH vì ảnh hưởng trực tiếp đến thu nhập|Tìm kiếm KH qua các kênh khác nhau (Hệ thống HomeX, Gọi điện thoại, Đăng bài Facebook,...)|Tiếp cận và tư vấn sản phẩm cho khách hàng|Thực hiện hợp đồng|Hỗ trợ các cửa hàng khác khi có yêu cầu từ quản lý|Gặp gỡ KH ở bên ngoài (quán cafe, nhà của KH) khi cần thiết|Làm việc tại shop bán xe máy hoặc cửa hàng bán điện thoại, đồ điện máy',),
		'Quyền lợi của SA': ('Thu nhập thực nhận bằng Tổng thu nhập gộp trừ đi Các khoản khấu trừ|Có cơ hội phát triển theo định hướng Người bán hàng chuyên nghiệp|Có cơ hội phát triển theo định hướng Nhà quản lý kinh doanh khu vực|Có cơ hội học tập bằng các khóa học trên E-learning, Workshop, Talkshow,...',),
	},
	('Chi tiết SA', 'Vai trò, trách nhiệm của SA'): {
		'SA trực thuộc mạng lưới kinh doanh (MLKD) và báo cáo trực tiếp cho quản lý kinh doanh khu vực (DSM)': ('Sơ đồ tổ chức phòng Sales',),
		'nan': ('Xây dựng mối quan hệ với cửa hàng',),
		'Là người trực tiếp mang nguồn thu nhập, lợi nhuận về cho công ty, đảm bảo mục tiêu kinh doanh với tỷ lệ rủi ro thấp nhất|Là đại sứ thương hiệu công ty, là chuyên gia tư vấn tài chính giúp KH có được những sản phẩm tài chính uy tín, chất lượng, dịch vụ tận tâm và phù hợp với nhu cầu|Là người đồng hành, xây dựng mối quan hệ tốt đẹp với đối tác và luôn chia sẻ, hỗ trợ với tinh thần win – win': ('Vai trò của SA',),
		'Tìm kiếm, tiếp cận, tư vấn các khoản vay đến KH với chất lượng dịch vụ chuyên nghiệp|Xây dựng mối quan hệ với các cửa hàng đối tác|Kiểm soát rủi ro gian lận|Tuân thủ các quy trình, quy định và chỉ thị từ cấp trên, công ty|Kiểm soát nợ xấu bằng cách nhận diện KH gian lận, kiểm tra chứng từ và theo dõi tình trạng đóng phí của KH': ('Trách nhiệm của SA',),
		'Được DSM phân công làm 2 ca 1 ngày|Sắp xếp thời gian hợp lý, phân chia công việc một cách rõ ràng và tận dụng tối đa một ngày làm việc|Ưu tiên nhất việc tìm kiếm và tiếp cận KH vì ảnh hưởng trực tiếp đến thu nhập|Tìm kiếm KH qua các kênh khác nhau (Hệ thống HomeX, Gọi điện thoại, Đăng bài Facebook,...)|Tiếp cận và tư vấn sản phẩm cho khách hàng|Thực hiện hợp đồng|Hỗ trợ các cửa hàng khác khi có yêu cầu từ quản lý|Gặp gỡ KH ở bên ngoài (quán cafe, nhà của KH) khi cần thiết|Làm việc tại shop bán xe máy hoặc cửa hàng bán điện thoại, đồ điện máy': ('Những việc làm hàng ngày của SA',),
		'Thu nhập thực nhận bằng Tổng thu nhập gộp trừ đi Các khoản khấu trừ|Có cơ hội phát triển theo định hướng Người bán hàng chuyên nghiệp|Có cơ hội phát triển theo định hướng Nhà quản lý kinh doanh khu vực|Có cơ hội học tập bằng các khóa học trên E-learning, Workshop, Talkshow,...': ('Quyền lợi của SA',),
	},
	('Thâm niên SA', 'Hệ số thâm niên'): {
		'Dưới 2 tháng': ('nan',),
		'Từ 2 - 4 tháng': ('nan',),
		'Từ 4 tháng trở lên': ('nan',),
		'Dưới 1 năm': (1.0,),
		'Từ 1- 5 năm': (1.2,),
		'Trên 5 năm': (1.5,),
	},
	('Hệ số thâm niên', 'Thâm niên SA'): {
		'nan': ('Dưới 2 tháng',),
		'nan': ('Từ 2 - 4 tháng',),
		'nan': ('Từ 4 tháng trở lên',),
		'1.0': ('Dưới 1 năm',),
		'1.2': ('Từ 1- 5 năm',),
		'1.5': ('Trên 5 năm',),
	},
	('Các khoản thu nhập và khấu trừ', 'Thuộc tính khoản thu nhập, khấu trừ', 'Công thức tính'): {
		'Phụ cấp, trợ cấp': ('nan', 'nan'),
		'Bảo hiểm bắt buộc': ('nan', 'nan'),
		'Thuế thu nhập cá nhân': ('nan', 'nan'),
		'Các khoản khấu trừ khác (nếu có)': ('nan', 'nan'),
		'Lương ngoài giờ': ('Chỉ làm ngoài giờ theo yêu cầu của cấp trên|Làm việc không quá: 200 giờ 1 năm, 4 giờ 1 ngày làm việc, 30 giờ 1 tháng|Sau khi làm việc, nhân viên sẽ được ưu tiên sắp xếp nghỉ bù, nếu không, số giờ làm thêm được quy thành tiền theo tỷ lệ|Lương ngoài giờ chưa bao gồm 100% lương ngày công hoặc theo chế độ phụ cấp công việc của từng phòng ban', 'Bằng 150% lương ngày công khi làm việc ngoài giờ trong ngày làm việc bình thường|Bằng 200% lương ngày công khi làm việc ngoài giờ trong ngày nghỉ tuần|Bằng 300% lương ngày công (trong đó 100% đã bao gồm trong tiền lương ngày lễ, tết) khi làm việc ngoài giờ trong ngày lễ, tết'),
		'Phụ cấp theo kết quả công việc, lương tháng 13': ('Phụ cấp/trợ cấp theo kết quả công việc được tính theo theo chính sách của công ty|Tùy thuộc vào kết quả kinh doanh của công ty, nhân viên có thể nhận được lương tháng 13|Nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 sẽ được tính theo tỷ lệ', 'Được tính theo chính sách của công ty, nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 được tính theo tỷ lệ'),
		'Các phúc lợi khác': ('Quà sinh nhật, quà cưới, quà cho bé mới sinh|Kiểm tra sức khỏe định kỳ hàng năm (1 lần 1 năm)|Bảo hiểm tai nạn 24 trên 24', 'nan'),
		'Lương thực tế trên hợp đồng': ('Lương trước thuế, chưa khấu trừ thuế thu nhập cá nhân và các khoản khấu trừ bắt buộc khác theo luật định|Chấm công từ ngày 1 đến ngày cuối tháng|Lương được chi trả từ ngày 1 đến ngày cuối tháng. Từ ngày 23 đến ngày cuối tháng, Công ty đã trả trước cho nhân viên và sẽ được điều chỉnh vào tháng sau nếu có thay đổi|Hình thức trả lương là chuyển khoản vào tài khoản cá nhân|Nhân viên mới vào công ty sau ngày 22, lương sẽ được trả vào tháng kế tiếp|Tài khoản cá nhân phải đứng tên của cá nhân nhân viên, không dùng tài khoản cá nhân của người khác|Chỉ chấp nhận trả lương vào tài khoản của các ngân hàng Vietcombank, Vietinbank, Đông Á, Techcombank, VPBank, ACB', 'nan'),
		'Thưởng cấp bậc': ('Có 4 cấp độ dành cho nhân viên bán hàng tương ứng với các mức thưởng|SA vẫn được giữ nguyên chức vụ trong suốt thời gian nghỉ thai sản nhưng sẽ không được nhận khoản tiền này|Khoản tiền này sẽ bắt đầu được tính khi SA quay trở lại làm việc sau thời kỳ nghỉ thai sản miễn là phải đáp ứng các tiêu chí theo qui định|Kết quả trung bình của 02 tháng trong tháng đầu tiên sau khi SA quay trở lại làm việc bằng tháng đầu tiên sau khi quay trở lại và 01 tháng trước nghỉ thai sản|Trong trường hợp SA không duy trì được tiêu chí cấp bậc hoặc bị đánh lỗi soft trigger, nhận thẻ vàng, 2 thư khiển trách trở lên, SA sẽ bị giáng cấp và mất khoản tiền này|Tháng tính thưởng bằng Tháng thưởng cộng 1', 'Doanh số tính cho SA thực hiện Bước 2 đối với CD, TW, CLX|Doanh số tính cho SA thực hiện Bước 1 và Bước 2 đối với ACL (trong trường hợp 1 SA cùng thực hiện cả Bước 1 và Bước 2 thì chỉ tính 1 lần)|Doanh số tính cho SA tạo hợp đồng đối với sản phẩm S.A.I|Doanh số tính cho SA thực hiện Bước 1 đối với sản phẩm Thẻ|Khoản cộng A trong công thức tính doanh số bằng Tổng khoản vay bao gồm phí bảo hiểm của CD, TW, CLX, ACL, S.A.I ký trong tháng thưởng cộng Số thẻ tín dụng được ký trong 1 tháng liền trước có phát sinh giao dịch trong tháng thưởng nhân 40 triệu VND|Khoản trừ B trong công thức tính doanh số bằng Tổng khoản vay bao gồm phí bảo hiểm của CD, TW, CLX, ACL, S.A.I bị hủy trong tháng thưởng cộng Số thẻ tín dụng đã được thưởng trong 1 tháng liền trước nhưng bị đóng trong tháng thưởng nhân 40 triệu VND|Doanh số bằng Khoản cộng A trừ Khoản trừ B theo quy định\n'),
	},
	('Thuộc tính khoản thu nhập, khấu trừ', 'Các khoản thu nhập và khấu trừ', 'Công thức tính'): {
		'nan': ('Các khoản khấu trừ khác (nếu có)', 'nan'),
		'Chỉ làm ngoài giờ theo yêu cầu của cấp trên|Làm việc không quá: 200 giờ 1 năm, 4 giờ 1 ngày làm việc, 30 giờ 1 tháng|Sau khi làm việc, nhân viên sẽ được ưu tiên sắp xếp nghỉ bù, nếu không, số giờ làm thêm được quy thành tiền theo tỷ lệ|Lương ngoài giờ chưa bao gồm 100% lương ngày công hoặc theo chế độ phụ cấp công việc của từng phòng ban': ('Lương ngoài giờ', 'Bằng 150% lương ngày công khi làm việc ngoài giờ trong ngày làm việc bình thường|Bằng 200% lương ngày công khi làm việc ngoài giờ trong ngày nghỉ tuần|Bằng 300% lương ngày công (trong đó 100% đã bao gồm trong tiền lương ngày lễ, tết) khi làm việc ngoài giờ trong ngày lễ, tết'),
		'Phụ cấp/trợ cấp theo kết quả công việc được tính theo theo chính sách của công ty|Tùy thuộc vào kết quả kinh doanh của công ty, nhân viên có thể nhận được lương tháng 13|Nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 sẽ được tính theo tỷ lệ': ('Phụ cấp theo kết quả công việc, lương tháng 13', 'Được tính theo chính sách của công ty, nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 được tính theo tỷ lệ'),
		'Quà sinh nhật, quà cưới, quà cho bé mới sinh|Kiểm tra sức khỏe định kỳ hàng năm (1 lần 1 năm)|Bảo hiểm tai nạn 24 trên 24': ('Các phúc lợi khác', 'nan'),
		'Lương trước thuế, chưa khấu trừ thuế thu nhập cá nhân và các khoản khấu trừ bắt buộc khác theo luật định|Chấm công từ ngày 1 đến ngày cuối tháng|Lương được chi trả từ ngày 1 đến ngày cuối tháng. Từ ngày 23 đến ngày cuối tháng, Công ty đã trả trước cho nhân viên và sẽ được điều chỉnh vào tháng sau nếu có thay đổi|Hình thức trả lương là chuyển khoản vào tài khoản cá nhân|Nhân viên mới vào công ty sau ngày 22, lương sẽ được trả vào tháng kế tiếp|Tài khoản cá nhân phải đứng tên của cá nhân nhân viên, không dùng tài khoản cá nhân của người khác|Chỉ chấp nhận trả lương vào tài khoản của các ngân hàng Vietcombank, Vietinbank, Đông Á, Techcombank, VPBank, ACB': ('Lương thực tế trên hợp đồng', 'nan'),
		'Có 4 cấp độ dành cho nhân viên bán hàng tương ứng với các mức thưởng|SA vẫn được giữ nguyên chức vụ trong suốt thời gian nghỉ thai sản nhưng sẽ không được nhận khoản tiền này|Khoản tiền này sẽ bắt đầu được tính khi SA quay trở lại làm việc sau thời kỳ nghỉ thai sản miễn là phải đáp ứng các tiêu chí theo qui định|Kết quả trung bình của 02 tháng trong tháng đầu tiên sau khi SA quay trở lại làm việc bằng tháng đầu tiên sau khi quay trở lại và 01 tháng trước nghỉ thai sản|Trong trường hợp SA không duy trì được tiêu chí cấp bậc hoặc bị đánh lỗi soft trigger, nhận thẻ vàng, 2 thư khiển trách trở lên, SA sẽ bị giáng cấp và mất khoản tiền này|Tháng tính thưởng bằng Tháng thưởng cộng 1': ('Thưởng cấp bậc', 'Doanh số tính cho SA thực hiện Bước 2 đối với CD, TW, CLX|Doanh số tính cho SA thực hiện Bước 1 và Bước 2 đối với ACL (trong trường hợp 1 SA cùng thực hiện cả Bước 1 và Bước 2 thì chỉ tính 1 lần)|Doanh số tính cho SA tạo hợp đồng đối với sản phẩm S.A.I|Doanh số tính cho SA thực hiện Bước 1 đối với sản phẩm Thẻ|Khoản cộng A trong công thức tính doanh số bằng Tổng khoản vay bao gồm phí bảo hiểm của CD, TW, CLX, ACL, S.A.I ký trong tháng thưởng cộng Số thẻ tín dụng được ký trong 1 tháng liền trước có phát sinh giao dịch trong tháng thưởng nhân 40 triệu VND|Khoản trừ B trong công thức tính doanh số bằng Tổng khoản vay bao gồm phí bảo hiểm của CD, TW, CLX, ACL, S.A.I bị hủy trong tháng thưởng cộng Số thẻ tín dụng đã được thưởng trong 1 tháng liền trước nhưng bị đóng trong tháng thưởng nhân 40 triệu VND|Doanh số bằng Khoản cộng A trừ Khoản trừ B theo quy định\n'),
	},
	('Công thức tính', 'Các khoản thu nhập và khấu trừ', 'Thuộc tính khoản thu nhập, khấu trừ'): {
		'nan': ('Lương thực tế trên hợp đồng', 'Lương trước thuế, chưa khấu trừ thuế thu nhập cá nhân và các khoản khấu trừ bắt buộc khác theo luật định|Chấm công từ ngày 1 đến ngày cuối tháng|Lương được chi trả từ ngày 1 đến ngày cuối tháng. Từ ngày 23 đến ngày cuối tháng, Công ty đã trả trước cho nhân viên và sẽ được điều chỉnh vào tháng sau nếu có thay đổi|Hình thức trả lương là chuyển khoản vào tài khoản cá nhân|Nhân viên mới vào công ty sau ngày 22, lương sẽ được trả vào tháng kế tiếp|Tài khoản cá nhân phải đứng tên của cá nhân nhân viên, không dùng tài khoản cá nhân của người khác|Chỉ chấp nhận trả lương vào tài khoản của các ngân hàng Vietcombank, Vietinbank, Đông Á, Techcombank, VPBank, ACB'),
		'Bằng 150% lương ngày công khi làm việc ngoài giờ trong ngày làm việc bình thường|Bằng 200% lương ngày công khi làm việc ngoài giờ trong ngày nghỉ tuần|Bằng 300% lương ngày công (trong đó 100% đã bao gồm trong tiền lương ngày lễ, tết) khi làm việc ngoài giờ trong ngày lễ, tết': ('Lương ngoài giờ', 'Chỉ làm ngoài giờ theo yêu cầu của cấp trên|Làm việc không quá: 200 giờ 1 năm, 4 giờ 1 ngày làm việc, 30 giờ 1 tháng|Sau khi làm việc, nhân viên sẽ được ưu tiên sắp xếp nghỉ bù, nếu không, số giờ làm thêm được quy thành tiền theo tỷ lệ|Lương ngoài giờ chưa bao gồm 100% lương ngày công hoặc theo chế độ phụ cấp công việc của từng phòng ban'),
		'Được tính theo chính sách của công ty, nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 được tính theo tỷ lệ': ('Phụ cấp theo kết quả công việc, lương tháng 13', 'Phụ cấp/trợ cấp theo kết quả công việc được tính theo theo chính sách của công ty|Tùy thuộc vào kết quả kinh doanh của công ty, nhân viên có thể nhận được lương tháng 13|Nhân viên chưa đủ 12 tháng làm việc, hoặc có điều chỉnh lương trong năm thì lương tháng 13 sẽ được tính theo tỷ lệ'),
	},
	('Vai trò, trách nhiệm của SA', 'Tác phong SA', 'Đánh giá tác phong'): {
		'Tác phong': ('mặc áo sơ mi đồng phục vào thứ 2 - thứ 7 và mặc áo thun Home Credit hoặc áo sơ mi đồng phục vào chủ nhật', 'nên'),
	},
	('Tác phong SA', 'Vai trò, trách nhiệm của SA', 'Đánh giá tác phong'): {
		'mặc đồng phục và mang thẻ nhân viên trong suốt thời gian làm việc': ('Tác phong', 'nên'),
		'mang giày bít gót, bít mũi, kiểu dáng đơn giản, độ cao vừa phải đối với nữ và mang giầy tây đối với nam': ('Tác phong', 'nên'),
		'giữ đồng phục sạch sẽ, gọn gàng, chỉnh tề': ('Tác phong', 'nên'),
		'cắt tóc ngắn, gọn gàng đối với nam và cột tóc gọn, có thể nhuộm tóc, nhưng chọn màu tối đối với nữ': ('Tác phong', 'nên'),
		'mặc quần, váy bằng chất liệu jean, thun hoặc kiểu dáng thể thao, quá chật hoặc quá rộng': ('Tác phong', 'không nên'),
		'mang giày thể thao, giày cao su, dép kẹp, giày quá nhiều màu nổi bật': ('Tác phong', 'không nên'),
		'dùng đồ trang sức, phụ kiện, nước hoa quá mức': ('Tác phong', 'không nên'),
		'để màu tóc quá nổi bật hoặc kiểu tóc quá khác biệt': ('Tác phong', 'không nên'),
		'mặc áo sơ mi đồng phục vào thứ 2 - thứ 7 và mặc áo thun Home Credit hoặc áo sơ mi đồng phục vào chủ nhật': ('Tác phong', 'nên'),
	},
	('Đánh giá tác phong', 'Vai trò, trách nhiệm của SA', 'Tác phong SA'): {
		'nên': ('Tác phong', 'mặc áo sơ mi đồng phục vào thứ 2 - thứ 7 và mặc áo thun Home Credit hoặc áo sơ mi đồng phục vào chủ nhật'),
		'không nên': ('Tác phong', 'để màu tóc quá nổi bật hoặc kiểu tóc quá khác biệt'),
	},
	('Vai trò, trách nhiệm của SA', 'Ứng xử với CH', 'Đánh giá ứng xử'): {
		'Xây dựng mối quan hệ với cửa hàng': ('Xem việc hướng dẫn khách hàng thủ tục thanh toán, phương thức bảo trì là nhiệm vụ của nhân viên cửa hàng', 'KHÔNG NÊN'),
	},
	('Ứng xử với CH', 'Vai trò, trách nhiệm của SA', 'Đánh giá ứng xử'): {
		'Thông báo lịch làm việc cho quản lý cửa hàng': ('Xây dựng mối quan hệ với cửa hàng', 'NÊN'),
		'Tuân thủ quy định, giờ giấc của cửa hàng': ('Xây dựng mối quan hệ với cửa hàng', 'NÊN'),
		'Hợp tác, hỗ trợ, tạo niềm tin & duy trì mối quan hệ tốt với cửa hàng': ('Xây dựng mối quan hệ với cửa hàng', 'NÊN'),
		'Hỗ trợ việc tư vấn sản phẩm của cửa hàng': ('Xây dựng mối quan hệ với cửa hàng', 'NÊN'),
		'Tìm hiểu đặc điểm & quyền lợi sản phẩm của cửa hàng': ('Xây dựng mối quan hệ với cửa hàng', 'NÊN'),
		'Hướng dẫn KH làm thủ tục thanh toán, bảo trì, cũng như giải đáp một số câu hỏi của KH trong những lúc cao điểm': ('Xây dựng mối quan hệ với cửa hàng', 'NÊN'),
		'Tùy tiện đến làm việc hoặc rời khỏi cửa hàng mà không thông báo quản lý': ('Xây dựng mối quan hệ với cửa hàng', 'KHÔNG NÊN'),
		'Đi làm trễ, về sớm so với quy định': ('Xây dựng mối quan hệ với cửa hàng', 'KHÔNG NÊN'),
		'Để mất lòng tin với cửa hàng': ('Xây dựng mối quan hệ với cửa hàng', 'KHÔNG NÊN'),
		'Chỉ tư vấn khách hàng có nhu cầu với sản phẩm của Home Credit': ('Xây dựng mối quan hệ với cửa hàng', 'KHÔNG NÊN'),
		'Chỉ nắm rõ đặc điểm & quyền lợi sản phẩm của Home Credit': ('Xây dựng mối quan hệ với cửa hàng', 'KHÔNG NÊN'),
		'Xem việc hướng dẫn khách hàng thủ tục thanh toán, phương thức bảo trì là nhiệm vụ của nhân viên cửa hàng': ('Xây dựng mối quan hệ với cửa hàng', 'KHÔNG NÊN'),
	},
	('Đánh giá ứng xử', 'Vai trò, trách nhiệm của SA', 'Ứng xử với CH'): {
		'NÊN': ('Xây dựng mối quan hệ với cửa hàng', 'Hướng dẫn KH làm thủ tục thanh toán, bảo trì, cũng như giải đáp một số câu hỏi của KH trong những lúc cao điểm'),
		'KHÔNG NÊN': ('Xây dựng mối quan hệ với cửa hàng', 'Xem việc hướng dẫn khách hàng thủ tục thanh toán, phương thức bảo trì là nhiệm vụ của nhân viên cửa hàng'),
	},
	('Vai trò, trách nhiệm của SA', 'Thâm niên SA'): {
	},
	('Thâm niên SA', 'Vai trò, trách nhiệm của SA'): {
	},
	('Vai trò, trách nhiệm của SA', 'Loại quyền lợi'): {
	},
	('Loại quyền lợi', 'Vai trò, trách nhiệm của SA'): {
	},
	('Trích lập dự phòng của doanh nghiệp', 'Chân dung khách hàng'): {
	},
	('Chân dung khách hàng', 'Trích lập dự phòng của doanh nghiệp'): {
	},
	('Mức trích lập dự phòng chung', 'Chân dung khách hàng'): {
	},
	('Chân dung khách hàng', 'Mức trích lập dự phòng chung'): {
	},
	('Nhóm nợ', 'Tỷ lệ trích lập dự phòng'): {
		'Nhóm nợ 1: Nợ đủ tiêu chuẩn': ('0%',),
		'Nhóm nợ 2: Nợ cần chú ý': ('5%',),
		'Nhóm nợ 3: Nợ dưới tiêu chuẩn': ('20%',),
		'Nhóm nợ 4: Nợ nghi ngờ': ('50%',),
		'Nhóm nợ 5: Nợ có khả năng mất vốn': ('100%',),
	},
	('Tỷ lệ trích lập dự phòng', 'Nhóm nợ'): {
		'0%': ('Nhóm nợ 1: Nợ đủ tiêu chuẩn',),
		'5%': ('Nhóm nợ 2: Nợ cần chú ý',),
		'20%': ('Nhóm nợ 3: Nợ dưới tiêu chuẩn',),
		'50%': ('Nhóm nợ 4: Nợ nghi ngờ',),
		'100%': ('Nhóm nợ 5: Nợ có khả năng mất vốn',),
	},
	('Chân dung khách hàng', 'Khoản nợ'): {
	},
	('Khoản nợ', 'Chân dung khách hàng'): {
	},
	('Quy định', 'Chi tiết quy định'): {
		'Tuân thủ về niêm yết tài liệu': ('Niêm yết các tài liệu: Thông tin lãi suất sản phẩm, phương pháp tính lãi, các loại phí, Hợp đồng theo mẫu, Điều kiện giao dịch chung, Các hình thức tiếp nhận góp ý, phản ánh, khiếu nại của KH, Tài liệu khác theo thông báo từ TINTIN',),
		'Tuân thủ về trưng bày POSM': ('Giữ POSM của mình luôn đẹp, gọn gàng, sạch sẽ',),
		'Tuân thủ về nguyên tắc tư vấn': ('Đảm bảo có xác nhận của KH về việc đã được công ty cung cấp đầy đủ thông tin để KH xem xét, quyết định trước khi ký kết hợp đồng',),
		'Ứng xử khi gặp cơ quan nhà nước và báo chí': ('Luôn giữ thái độ niềm nở, vui vẻ, hợp tác và bình tĩnh',),
		'Tuân thủ Nghị định 91 về nguyên tắc gọi điện, email, gửi tin nhắn tư vấn, quảng cáo': ('Chỉ gửi tin nhắn trong khoảng thời gian từ 07 - 22 giờ mỗi ngày, gọi điện thoại quảng cáo từ 08 - 17 giờ mỗi ngày trừ trường hợp đã có thỏa thuận khác với KH',),
	},
	('Chi tiết quy định', 'Quy định'): {
		'Niêm yết các tài liệu: Thông tin lãi suất sản phẩm, phương pháp tính lãi, các loại phí, Hợp đồng theo mẫu, Điều kiện giao dịch chung, Các hình thức tiếp nhận góp ý, phản ánh, khiếu nại của KH, Tài liệu khác theo thông báo từ TINTIN': ('Tuân thủ về niêm yết tài liệu',),
		'Giữ POSM của mình luôn đẹp, gọn gàng, sạch sẽ': ('Tuân thủ về trưng bày POSM',),
		'Đảm bảo có xác nhận của KH về việc đã được công ty cung cấp đầy đủ thông tin để KH xem xét, quyết định trước khi ký kết hợp đồng': ('Tuân thủ về nguyên tắc tư vấn',),
		'Luôn giữ thái độ niềm nở, vui vẻ, hợp tác và bình tĩnh': ('Ứng xử khi gặp cơ quan nhà nước và báo chí',),
		'Chỉ gửi tin nhắn trong khoảng thời gian từ 07 - 22 giờ mỗi ngày, gọi điện thoại quảng cáo từ 08 - 17 giờ mỗi ngày trừ trường hợp đã có thỏa thuận khác với KH': ('Tuân thủ Nghị định 91 về nguyên tắc gọi điện, email, gửi tin nhắn tư vấn, quảng cáo',),
	},
	('Thâm niên SA', 'Các mục tiêu doanh số'): {
		'Dưới 2 tháng': ('Tổng doanh số tháng từ 150 triệu của các sản phẩm CD, TW, CLX ở bước Ký',),
		'Từ 2 - 4 tháng': ('Tổng doanh số tháng từ 225 triệu của các sản phẩm CD, TW, CLX ở bước Ký',),
		'Từ 4 tháng trở lên': ('Tổng doanh số tháng từ 300 triệu của các sản phẩm CD, TW, CLX ở bước Ký',),
	},
	('Các mục tiêu doanh số', 'Thâm niên SA'): {
		'Tổng doanh số tháng từ 150 triệu của các sản phẩm CD, TW, CLX ở bước Ký': ('Dưới 2 tháng',),
		'Tổng doanh số tháng từ 225 triệu của các sản phẩm CD, TW, CLX ở bước Ký': ('Từ 2 - 4 tháng',),
		'Tổng doanh số tháng từ 300 triệu của các sản phẩm CD, TW, CLX ở bước Ký': ('Từ 4 tháng trở lên',),
	},
	('Các cấp độ của SA', 'Tiêu chí lên cấp bậc'): {
		'Senior SA (SSA)': ('Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 320 triệu VND',),
		'Master SA (MSA)': ('Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 600 triệu VND',),
		'Warrior SA (WSA)': ('Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 900 triệu VND',),
		'DSM': ('Thâm niên từ 1 năm trở lên',),
	},
	('Tiêu chí lên cấp bậc', 'Các cấp độ của SA'): {
		'Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 320 triệu VND': ('Senior SA (SSA)',),
		'Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 600 triệu VND': ('Master SA (MSA)',),
		'Doanh số thực đạt trung bình của 2 tháng liên tiếp (bao gồm cả tháng thưởng) từ 900 triệu VND': ('Warrior SA (WSA)',),
		'Thâm niên từ 1 năm trở lên': ('DSM',),
	},
	('Loại quyền lợi', 'Các khoản thu nhập và khấu trừ'): {
		'Tổng thu nhập gộp': ('Phụ cấp, trợ cấp',),
		'Các khoản khấu trừ': ('Bảo hiểm bắt buộc',),
	},
	('Các khoản thu nhập và khấu trừ', 'Loại quyền lợi'): {
		'Phụ cấp, trợ cấp': ('Tổng thu nhập gộp',),
		'Bảo hiểm bắt buộc': ('Các khoản khấu trừ',),
	},
	('Tổng quan về công ty', 'Chân dung KH'): {
		'Khách hàng của ngân hàng': ('Có hợp đồng lao động',),
		'Khách hàng đủ điều kiện làm hợp đồng với Home Credit': ('Từ công nhân đến người kinh doanh, sinh viên còn đi học hoặc đã tốt nghiệp, người lao động phổ thông',),
	},
	('Chân dung KH', 'Tổng quan về công ty'): {
		'Có hợp đồng lao động': ('Khách hàng của ngân hàng',),
		'Từ công nhân đến người kinh doanh, sinh viên còn đi học hoặc đã tốt nghiệp, người lao động phổ thông': ('Khách hàng đủ điều kiện làm hợp đồng với Home Credit',),
	},
	('Nhóm sản phẩm', 'Tên sản phẩm', 'Lợi ích sản phẩm', 'Thuật ngữ sản phẩm'): {
		'Vay trả góp mua hàng hóa tại shop': ('Vay trả góp xe máy - TW', 'nan', 'nan'),
		'Vay trả góp tiền mặt - CL': ('Tiền mặt bán chéo - CLX', 'nan', 'nan'),
		'Thẻ tín dụng - CC': ('Thẻ tín dụng CCX', 'nan', 'nan'),
		'Bảo hiểm bán kèm': ('An tâm tài chính - PPI', 'nan', 'nan'),
		'Bảo hiểm độc lập': ('Sức khoẻ nội trú - ITP', 'nan', 'nan'),
	},
	('Tên sản phẩm', 'Nhóm sản phẩm', 'Lợi ích sản phẩm', 'Thuật ngữ sản phẩm'): {
		'Vay trả góp xe máy - TW': ('Vay trả góp mua hàng hóa tại shop', 'nan', 'nan'),
		'Tiền mặt bán chéo - CLX': ('Vay trả góp tiền mặt - CL', 'nan', 'nan'),
		'Thẻ tín dụng CCX': ('Thẻ tín dụng - CC', 'nan', 'nan'),
		'An tâm tài chính - PPI': ('Bảo hiểm bán kèm', 'nan', 'nan'),
		'Sức khoẻ nội trú - ITP': ('Bảo hiểm độc lập', 'nan', 'nan'),
	},
	('Lợi ích sản phẩm', 'Nhóm sản phẩm', 'Tên sản phẩm', 'Thuật ngữ sản phẩm'): {
		'nan': ('Vay trả góp mua hàng hóa tại shop', 'Vay trả góp xe máy - TW', 'nan'),
		'nan': ('Vay trả góp tiền mặt - CL', 'Tiền mặt bán chéo - CLX', 'nan'),
		'nan': ('Thẻ tín dụng - CC', 'Thẻ tín dụng CCX', 'nan'),
		'nan': ('Bảo hiểm bán kèm', 'An tâm tài chính - PPI', 'nan'),
		'nan': ('Bảo hiểm độc lập', 'Sức khoẻ nội trú - ITP', 'nan'),
	},
	('Thuật ngữ sản phẩm', 'Nhóm sản phẩm', 'Tên sản phẩm', 'Lợi ích sản phẩm'): {
		'nan': ('Vay trả góp mua hàng hóa tại shop', 'Vay trả góp xe máy - TW', 'nan'),
		'nan': ('Vay trả góp tiền mặt - CL', 'Tiền mặt bán chéo - CLX', 'nan'),
		'nan': ('Thẻ tín dụng - CC', 'Thẻ tín dụng CCX', 'nan'),
		'nan': ('Bảo hiểm bán kèm', 'An tâm tài chính - PPI', 'nan'),
		'nan': ('Bảo hiểm độc lập', 'Sức khoẻ nội trú - ITP', 'nan'),
	},
	('Các khoản thu nhập và khấu trừ', 'Các cấp độ của SA', 'Thâm niên SA', 'Số tiền thưởng cấp bậc'): {
		'Thưởng cấp bậc': ('SA', 'nan', 'Không có thưởng cấp bậc'),
	},
	('Các cấp độ của SA', 'Các khoản thu nhập và khấu trừ', 'Thâm niên SA', 'Số tiền thưởng cấp bậc'): {
		'Senior SA (SSA)': ('Thưởng cấp bậc', 'Trên 5 năm', '900.000 đồng một tháng'),
		'Master SA (MSA)': ('Thưởng cấp bậc', 'Trên 5 năm', '2.700.000 đồng một tháng'),
		'Warrior SA (WSA)': ('Thưởng cấp bậc', 'Trên 5 năm', '5.400.000 đồng một tháng'),
		'SA': ('Thưởng cấp bậc', 'nan', 'Không có thưởng cấp bậc'),
	},
	('Thâm niên SA', 'Các khoản thu nhập và khấu trừ', 'Các cấp độ của SA', 'Số tiền thưởng cấp bậc'): {
		'Dưới 1 năm': ('Thưởng cấp bậc', 'Warrior SA (WSA)', '3.600.000 đồng một tháng'),
		'Từ 1- 5 năm': ('Thưởng cấp bậc', 'Warrior SA (WSA)', '4.320.000 đồng một tháng'),
		'Trên 5 năm': ('Thưởng cấp bậc', 'Warrior SA (WSA)', '5.400.000 đồng một tháng'),
		'nan': ('Thưởng cấp bậc', 'SA', 'Không có thưởng cấp bậc'),
	},
	('Số tiền thưởng cấp bậc', 'Các khoản thu nhập và khấu trừ', 'Các cấp độ của SA', 'Thâm niên SA'): {
		'600.000 đồng một tháng': ('Thưởng cấp bậc', 'Senior SA (SSA)', 'Dưới 1 năm'),
		'720.000 đồng một tháng': ('Thưởng cấp bậc', 'Senior SA (SSA)', 'Từ 1- 5 năm'),
		'900.000 đồng một tháng': ('Thưởng cấp bậc', 'Senior SA (SSA)', 'Trên 5 năm'),
		'1.800.000 đồng một tháng': ('Thưởng cấp bậc', 'Master SA (MSA)', 'Dưới 1 năm'),
		'2.160.000 đồng một tháng': ('Thưởng cấp bậc', 'Master SA (MSA)', 'Từ 1- 5 năm'),
		'2.700.000 đồng một tháng': ('Thưởng cấp bậc', 'Master SA (MSA)', 'Trên 5 năm'),
		'3.600.000 đồng một tháng': ('Thưởng cấp bậc', 'Warrior SA (WSA)', 'Dưới 1 năm'),
		'4.320.000 đồng một tháng': ('Thưởng cấp bậc', 'Warrior SA (WSA)', 'Từ 1- 5 năm'),
		'5.400.000 đồng một tháng': ('Thưởng cấp bậc', 'Warrior SA (WSA)', 'Trên 5 năm'),
		'Không có thưởng cấp bậc': ('Thưởng cấp bậc', 'SA', 'nan'),
	},
	('Chân dung khách hàng', 'Nhóm nợ', 'Điều kiện xác định nhóm nợ'): {
		'Khách hàng 1': ('Nhóm nợ 1: Nợ đủ tiêu chuẩn', 'Có khả năng trả nợ cao nhất, khi khoản nợ của các nhóm này đều chưa đến hạn thanh toán'),
		'Khách hàng 2': ('Nhóm nợ 2: Nợ cần chú ý', 'Đã chậm thanh toán khoản nợ đến 90 ngày theo nội dung hợp đồng tín dụng'),
		'Khách hàng 3': ('Nhóm nợ 3: Nợ dưới tiêu chuẩn', 'Đã chậm thanh toán khoản nợ từ 91 ngày đến 180 ngày, và khoản nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ nhưng khoản nợ được gia hạn lần đầu vẫn còn trong hạn'),
		'Khách hàng 4': ('Nhóm nợ 4: Nợ nghi ngờ', 'Có độ tín nhiệm rất thấp khi đã quá hạn trả nợ từ 181 ngày đến 360 ngày, bên nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ lần đầu, tuy nhiên tiếp tục quá hạn trả nợ đến 90 ngày đối với thời gian trả nợ đã được cơ cấu lần đầu'),
		'Khách hàng 5': ('Nhóm nợ 5: Nợ có khả năng mất vốn', 'Có khả năng thu hồi nợ rất thấp, khoản nợ đã quá hạn trên 360 ngày, khoản nợ cơ cấu lại thời hạn trả nợ lần đầu quá hạn từ 91 ngày trở lên theo thời hạn trả nợ được cơ cấu lại lần đầu'),
	},
	('Nhóm nợ', 'Chân dung khách hàng', 'Điều kiện xác định nhóm nợ'): {
		'Nhóm nợ 1: Nợ đủ tiêu chuẩn': ('Khách hàng 1', 'Có khả năng trả nợ cao nhất, khi khoản nợ của các nhóm này đều chưa đến hạn thanh toán'),
		'Nhóm nợ 2: Nợ cần chú ý': ('Khách hàng 2', 'Đã chậm thanh toán khoản nợ đến 90 ngày theo nội dung hợp đồng tín dụng'),
		'Nhóm nợ 3: Nợ dưới tiêu chuẩn': ('Khách hàng 3', 'Đã chậm thanh toán khoản nợ từ 91 ngày đến 180 ngày, và khoản nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ nhưng khoản nợ được gia hạn lần đầu vẫn còn trong hạn'),
		'Nhóm nợ 4: Nợ nghi ngờ': ('Khách hàng 4', 'Có độ tín nhiệm rất thấp khi đã quá hạn trả nợ từ 181 ngày đến 360 ngày, bên nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ lần đầu, tuy nhiên tiếp tục quá hạn trả nợ đến 90 ngày đối với thời gian trả nợ đã được cơ cấu lần đầu'),
		'Nhóm nợ 5: Nợ có khả năng mất vốn': ('Khách hàng 5', 'Có khả năng thu hồi nợ rất thấp, khoản nợ đã quá hạn trên 360 ngày, khoản nợ cơ cấu lại thời hạn trả nợ lần đầu quá hạn từ 91 ngày trở lên theo thời hạn trả nợ được cơ cấu lại lần đầu'),
	},
	('Điều kiện xác định nhóm nợ', 'Chân dung khách hàng', 'Nhóm nợ'): {
		'Có khả năng trả nợ cao nhất, khi khoản nợ của các nhóm này đều chưa đến hạn thanh toán': ('Khách hàng 1', 'Nhóm nợ 1: Nợ đủ tiêu chuẩn'),
		'Đã chậm thanh toán khoản nợ đến 90 ngày theo nội dung hợp đồng tín dụng': ('Khách hàng 2', 'Nhóm nợ 2: Nợ cần chú ý'),
		'Đã chậm thanh toán khoản nợ từ 91 ngày đến 180 ngày, và khoản nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ nhưng khoản nợ được gia hạn lần đầu vẫn còn trong hạn': ('Khách hàng 3', 'Nhóm nợ 3: Nợ dưới tiêu chuẩn'),
		'Có độ tín nhiệm rất thấp khi đã quá hạn trả nợ từ 181 ngày đến 360 ngày, bên nợ đã được tổ chức tín dụng, chi nhánh ngân hàng điều chỉnh kỳ hạn trả nợ lần đầu, tuy nhiên tiếp tục quá hạn trả nợ đến 90 ngày đối với thời gian trả nợ đã được cơ cấu lần đầu': ('Khách hàng 4', 'Nhóm nợ 4: Nợ nghi ngờ'),
		'Có khả năng thu hồi nợ rất thấp, khoản nợ đã quá hạn trên 360 ngày, khoản nợ cơ cấu lại thời hạn trả nợ lần đầu quá hạn từ 91 ngày trở lên theo thời hạn trả nợ được cơ cấu lại lần đầu': ('Khách hàng 5', 'Nhóm nợ 5: Nợ có khả năng mất vốn'),
	},
}