knowledge_vertices = {	'Tính năng nổi bật': [
		'Tích lũy điểm thưởng',
		'Bảo hiểm du lịch toàn cầu',
		'Dịch vụ chọn số thẻ đẹp',
		'Mua hàng trả góp',
		'Tặng đặc quyền miễn phí',
		'Dịch vụ thay thế thẻ khẩn cấp',
		'Dịch vụ tin nhắn BSMS',
		'Dịch vụ hỗ trợ khách hàng 24-7',
	],
	'Loại giao dịch': [
		'Trên máy ATM',
		'Trên thiết bị chấp nhận thanh toán POS',
		'Dịch vụ khác',
		'Lưu ý khi giao dịch',
		'Danh sách ngân hàng kết nối',
		'Các kênh hỗ trợ trong quá trình sử dụng thẻ',
		'Trên máy CRM X',
		'Trên máy CRM X và CRM có biểu tượng các Tổ chức thẻ mà X là thành viên hoặc có hợp tác',
		'Trên máy ATM/POS',
		'Trực tuyến/trên máy POS',
	],
	'Trạng thái thẻ': [
		'Duy trì cho đến hết thời hạn hiệu lực thẻ hoặc theo thông báo của X',
		'Đang cơ cấu và dự kiến điều chỉnh theo tiến độ hợp tác',
		'Không phát hành mới, duy trì thẻ hiện hữu cho đến hết thời hạn thẻ, chuyển đổi sang thẻ MC-TPV mã 37',
		'Dừng phát hành mới, giữ nguyên mã sản phẩm và sử dụng phôi thẻ Mastercard Ready',
		'Dừng phát hành mới, chuyển đổi sang thẻ X Smart chip vật lý hoặc phi vật lý',
		'Đang cơ cấu',
		'Dừng phát hành mới, giữ nguyên mã sản phẩm và sử dụng phôi thẻ Visa Cashback 360',
		'Dừng phát hành mới, tư vấn chuyển đổi KH sang thẻ định danh KHCC',
		'Dừng phát hành mới, giữ nguyên mã sản phẩm và sử dụng phôi thẻ Visa Flexi',
		'Dừng phát hành mới, đổi tên và hình ảnh như thẻ Visa Easy',
	],
	'Hình thức thẻ': [
		'Vật lý',
		'Phi vật lý',
		'Vật lý và Phi vật lý',
	],
	'Loại phí': [
		'Phí phát hành lần đầu',
		'Phí phát hành lại do hỏng, mất',
		'Phí phát hành nhanh',
		'Phí trả thẻ về địa chỉ - không áp dụng cho thẻ TPV',
		'Phí thường niên',
		'Phí xử lý giao dịch tại thiết bị chấp nhận thẻ nước ngoài',
		'Phí xử lý giao dịch tại thiết bị chấp nhận thẻ nước ngoài thẻ JCB Ultimate',
		'Phí chuyển đổi ngoại tệ',
		'Phí phạt chậm thanh toán',
		'Phí thông báo thẻ mất cắp thất lạc qua Tổ chức thẻ',
		'Phí xác nhận Hạn mức tín dụng thẻ',
		'Phí tra soát trong trường hợp KH khiếu nại sai',
		'Phí cấp sao kê chi tiết tài khoản theo yêu cầu chủ thẻ',
		'Phí trả góp linh hoạt: Phí thu chủ thẻ khi đăng ký trả góp trực tiếp với X',
		'Phí ngừng sử dụng thẻ theo yêu cầu của KH',
		'Phí chuyển khoản trong cùng hệ thống',
		'Phí in hóa đơn tại ATM',
		'Phí rút tiền mặt tại NH nước ngoài có biểu tượng NAPAS',
		'Phí vấn tin số dư trên POS Ngân hàng khác',
		'Phí ứng, rút tiền mặt qua POS',
		'Phí thanh toán hàng hóa dịch vụ tại POS',
		'Phí giao dịch thanh toán trực tuyến tại các Website chấp nhận thẻ ghi nợ nội địa X',
		'Phí nạp tiền vào thẻ',
		'Phí gia hạn thẻ',
		'Phí cấp hạn mức tín dụng tạm thời, thay đổi hạn mức tín dụng, thay đổi hình thức thế chấp',
		'Phí kích hoat lại thẻ trên lần',
		'Phí cấp lại PIN trên lần',
		'Phí thay đổi tài khoản liên kết trên lần',
		'Phí chuyển tiền nhanh liên ngân hàng 24 trên 7 trên ATM X dưới 500.000VND',
		'Phí chuyển tiền nhanh liên ngân hàng 24 trên 7 trên ATM X 500.001-2.000.000VND',
		'Phí chuyển tiền nhanh liên ngân hàng 24 trên 7 trên ATM X 2.000.001-10 triệu VND',
		'Phí chuyển tiền nhanh liên ngân hàng 24 trên 7 trên ATM X trên 10 triệu VND',
		'Phí rút tiền mặt tại ATM hoặc POS trong nước',
		'Phí rút tiền mặt tại ATM hoặc POS X',
		'Chuyển khoản trong nội bộ X hoặc giao dịch tại ATM ngân hàng kết nối',
		'Phí vấn tin tài khoản hoặc In chứng từ vấn tin tài khoản tại NH trong nước',
		'Phí vấn tin tài khoản hoặc In chứng từ vấn tin tài khoản tại NH nước ngoài',
		'Phí cấp bản sao chứng từ giao dịch tại đại lý hoặc đơn vị chấp nhận thẻ của X',
		'Phí cấp bản sao chứng từ giao dịch tại đại lý hoặc đơn vị chấp nhận thẻ của NH khác',
	],
	'Thông tin chung về thẻ': [
		'Tài khoản liên kết',
		'Kênh thanh toán dư nợ',
		'Số lượng thẻ phát hành tối đa theo KH',
		'Phân loại sản phẩm',
		'Hạn mức giao dịch hoặc hạn mức tín dụng',
		'Mô tả sản phẩm',
	],
	'Chi tiết giao dịch': [
		'Rút tiền mặt bằng thẻ',
		'Rút tiền qua mã QR bằng thiết bị di động thông minh sử dụng ứng dụng X SmartBanking, trường hợp thẻ liên kết tài khoản thấu chi: chỉ cho phép rút tiền trên số dư thực có',
		'Đổi PIN',
		'Vấn tin số dư tài khoản',
		'In sao kê rút gọn, in hóa đơn giao dịch',
		'Thanh toán hoá đơn',
		'Nộp tiền vào tài khoản thanh toán',
		'Nộp tiền để gửi tiền tiết kiệm có kỳ hạn FD',
		'Chuyển khoản từ tài khoản CA để gửi tiền tiết kiệm có kỳ hạn',
		'Vấn tin tiền gửi tiết kiệm tài khoản FD',
		'Tất toán tiền gửi tiết kiệm tài khoản FD',
		'Mở thêm mới tài khoản tiền gửi CA',
		'Thanh toán hàng hóa dịch vụ',
		'Giao dịch hủy',
		'Ứng rút tiền mặt, vấn tin số dư tài khoản tại POS X và các POS có biểu tượng Napas',
		'Rút tiền trên POS X đặt tại các Chi nhánh X',
		'Đổi PIN trên POS - dòng Ingenico iWL220, iCT220, Tetra đặt tại Chi nhánh X',
		'Ứng rút tiền mặt, hủy ứng rút tiền mặt tại POS X và các POS có biểu tượng Mastercard',
		'Giao dịch điều chỉnh, đặt cọc, refund trên POS',
		'Thanh toán hóa đơn tại website kết nối cổng thanh toán với X, không liên kết ví điện tử',
		'Giao dịch thẻ tại nước ngoài, hoặc đồng tiền giao dịch khác',
		'Không áp dụng thanh toán trực tuyến E-commerce',
		'Chỉ áp dụng thanh toán hàng hóa dịch vụ  trên thiết bị POS có biểu tượng VISA trong nước',
		'Chuyển tiền từ tài khoản liên kết thẻ đến tài khoản, thẻ ngân hàng khác trong liên minh Napas theo thời gian thực, ngoại trừ tài khoản ngoại tệ',
		'Nhận chuyển tiền từ tài khoản, thẻ ngân hàng khác trong liên minh Napas tới số thẻ theo thời gian thực, ngoại trừ tài khoản ngoại tệ',
		'Tokenization thẻ trên hệ thống, ứng dụng của các đối tác: liên kết,  hủy liên kết thẻ X với tài khoản người dùng, nạp tiền, rút tiền, thanh toán, hoàn trả GD',
		'Ứng tiền mặt, refund, điều chỉnh, đặt cọc, hoàn tất đặt cọc, MOTO tại POS X và POS có biểu tượng tổ chức thẻ quốc tế',
		'Thanh toán trực tuyến tại các website, ứng dụng TMDT chấp nhận thanh toán thẻ có biểu tượng tương ứng biểu tượng trên thẻ',
		'Thanh toán hàng hóa dịch vụ hoặc Rút tiền mặt tại tất cả các ATM, POS, Máy giao dịch tự động có biểu tượng tương ứng biểu tượng trên thẻ',
		'Không áp dụng ứng hoặc rút tiền mặt',
		'Chuyển tiền nhanh liên ngân hàng 24/7',
		'Chuyển khoản nội bộ X',
		'Thanh toán hàng hóa, dịch vụ không nhập PIN',
		'Chuyển khoản',
		'Ứng tiền mặt',
	],
	'Các loại khách hàng': [
		'Chủ thẻ >15 tuổi hạn mức cao',
		'Chủ thẻ >15 tuổi hạn mức thông thường',
		'Chủ thẻ đủ 6 -  chưa đủ 11 tuổi',
		'Chủ thẻ đủ 11 -  chưa đủ 15 tuổi',
		'KH có tài khoản thanh toán mở tại X và có nhu cầu sử dụng thẻ ghi nợ cho mục đích rút tiền, chi tiêu, thanh toán ở phạm vi trong nước',
		'KH có đăng ký dịch vụ SmartBanking, mong muốn sử dụng dịch vụ thẻ ghi nợ nội địa mà không muốn mang thêm thẻ vật lý',
		'KH có tài khoản thanh toán mở tại X và có mức chi tiêu thanh toán cao, muốn được ưu đãi từ các chính sách loyalty do X cung cấp',
		'KH thuộc phân đoạn Private theo phân đoạn KHCN của X',
		'KH thuộc phân đoạn Premier theo phân đoạn KHCN của X',
		'KH thuộc phân đoạn KH thân thiết theo phân đoạn KHCN của X',
		'KH mới bắt đầu sử dụng thẻ, nhu cầu thanh toán cơ bản, ưa thích lãi suất và phí thấp',
		'Thu phí viên của các công ty thu phí dịch vụ định kỳ như bảo hiểm, điện nước, viễn thông…',
		'KH đăng ký như thẻ quà tặng nhưng chưa có nhu cầu đăng ký thông tin cá nhân định danh - mở CIF tại Ngân hàng',
		'KH tổ chức mở tài khoản tiền gửi thanh toán tại X, có nhu cầu sử dụng phương thức thanh toán tiện lợi và hỗ trợ quản lý chi phí của tổ chức',
		'KH tổ chức thường xuyên phát sinh nhu cầu đi công tác, làm việc tại nước ngoài',
		'Doanh nghiệp đã được X cấp hạn mức tín dụng',
		'Doanh nghiệp đang có quan hệ tín dụng, quan hệ tiền gửi và sản phẩm dịch vụ khác tại X',
		'Doanh nghiệp tại các Khu công nghiệp, doanh nghiệp có yếu tố nước ngoài',
		'Các đơn vị uy tín, có quy mô KH, CBNV lớn, có nhu cầu phát hành thẻ ngân hàng tích hợp thông tin KH, CBNV thuộc quản lý của đơn vị đó',
		'KH có tài khoản thanh toán mở tại X và nhu cầu sử dụng thẻ ghi nợ cho nhu cầu chi tiêu, thanh toán trực tiếp, trực tuyến trong nước và nước ngoài',
		'KH không thuộc phân đoạn KH cao cấp của X nhưng có nhu cầu trải nghiệm đặc quyền phong cách sống: Golf, Spa, Lounge, Fast track…',
		'KH có thu nhập cao 40 tr.đồng 1 tháng trở lên và chi tiêu cao cấp hơn so với chủ thẻ hạng Platinum, tiệm cận với phận khúc KHCC của X',
		'KH với mức thu nhập từ 10 triệu đồng 1 tháng trở lên',
		'KH với mức thu nhập từ 5 triệu đồng 1 tháng trở lên',
		'KH ưa thích tiêu dùng thiết yếu hàng ngày',
		'KH ưa thích thanh toán trực tuyến - online',
		'KH ưa thích lãi suất và phí thấp, có nhu cầu để lại dư nợ',
		'KH ưa thích tiêu dùng các lĩnh vực du lịch: mua sắm tại Cửa hàng miễn thuế, mua vé máy bay, giao dịch nước ngoàiKH',
		'KH có nhu cầu sử dụng thẻ quốc tế Visa nhanh chóng, thuận tiện, thủ tục đơn giản hơn thẻ ghi nợ và thẻ tín dụng quốc tế',
	],
	'Lợi ích KH': [
		'An toàn, thuận tiện khi thanh toán, loại bỏ rủi ro khi mang theo tiền mặt',
		'Tận dụng được các ưu đãi, khuyến mại của ngân hàng, tổ chức thẻ và các đối tác liên kết',
		'Thuận tiện khi thanh toán',
		'Tận dụng được các đặc quyền, ưu đãi khuyến mại của ngân hàng, tổ chức thẻ quốc tế và các đối tác liên kết',
		'Tận dụng nguồn vốn của ngân hàng với thời gian ân hạn theo chính sách từng thời kỳ',
		'Đăng ký thẻ trả trước vô danh như thẻ quà tặng nhưng chưa có nhu cầu đăng ký thông tin cá nhân định danh tại Ngân hàng',
		'Đăng ký phát hành và sử dụng thẻ quốc tế mang thương hiệu Visa nhanh chóng, thuận tiện, quản lý chi tiêu trong phạm vi số dư tiền trên thẻ mà khách hàng mong muốn sử dụng',
		'Thủ tục phát hành thẻ và nhận thẻ đơn giản so với các sản phẩm thẻ ghi nợ và tín dụng quốc tế',
		'Đơn giản hóa thủ tục hành chính khi tạm ứng công tác phí',
		'Không cần quy đổi ngoại tệ khi cán bộ đi công tác nước ngoài',
		'Dễ dàng thanh toán tại hàng chục triệu điểm chấp nhận thẻ trên toàn cầu',
		'Chi tiêu trước, trả tiền sau, miễn lãi đến 45 ngày',
		'Gia tăng bảo mật với công nghệ Chip theo chuẩn EVM-VCCS và trải nghiệm thanh toán liền mạch với tính năng thanh toán không chạm: contactless',
		'Quản lý chi tiêu dễ dàng thông qua các chương trình phần mềm, tin nhắn SMS-OTT, email, Smartbanking',
	],
	'Mã SP': [
		'7',
		'34',
		'88',
		'66',
		'68',
		'43',
		'16',
		'42',
		'06',
		'38',
		'03',
		'37',
		'18',
		'01; 02',
		'20',
		'1001',
		'2001; 2011; 2002',
		'21',
		'19',
		'I5-CB TONG CONG TY ACV',
		'I6-CAN BO GOERTEK VIN',
		'I7-NGUOI NHAN TRO CAP ASXH',
		'DP01-OLD_Thẻ Chip VL ACV',
		'DP02-OLD_Thẻ Chip VL MPRT X',
		'DP03-OLD_Thẻ Chip VL ASXH',
		'B0-THE LIEN KET CHIP',
		'DS04-OLD_Thẻ Chip VL Liên kết',
		'B1-THE PHI VAT LY',
		'DG05-OLD_Thẻ Chip Phi Vật lý',
		'B4-THE VAT LY ONLINE',
		'DG06-OLD_Thẻ Chip VL online',
		'I0-Cho KH trả lương và vãng lai',
		'I2-KH VANG LAI',
		'I8-KHACH HANG SU DUNG TK USD',
		'DG07-OLD_Thẻ Chip VL',
		'B6-THE LIEN KET CHIP',
		'B2-THE PHI VAT LY',
		'B3-THE PHI VAT LY',
		'B5-THE VAT LY ONLINE',
		'I1-Cho KH trả lương và vãng lai',
		'B7-Cho KH trả lương và vãng lai',
		'B8-Cho KH trả lương và vãng lai',
		'I3-KH VANG LAI',
		'I4-KH VANG LAI',
		'I9-KHACH HANG SU DUNG TK USD',
		'DG08-OLD_Thẻ Chip VL CD',
		'D3-THE CHUYEN DOI D3',
		'D4-THE CHUYEN DOI D4',
		'B9-THE CHUYEN DOI B9',
		'D9-THE CHUYEN DOI D9',
		'D2-THE CHUYEN DOI D2',
		'DG09-OLD_Thẻ Chip Phi VL',
		'H9-Miễn phí rút tiền X-NAPAS',
		'DP10-OLD_Thẻ Chip VL MPRT',
		'A1-ACV CARDD-CTY CANG HANG KHONG VN',
		'MP01-Thẻ từ ACV',
		'A2-THE GOERTEK VINA',
		'MP02-Thẻ từ Goertek',
		'A3-THE NHAN TRO CAP (ASXH)',
		'MP03-Thẻ từ ASXH',
		'PA-HARMONY CARD',
		'T1-FOR FOREIGN CURRENCY CARD',
		'MP04-Thẻ từ Harmony',
		'G3-ETRANS GOLD CARD',
		'SP-ETRANS SILVER CARD',
		'V6-FOR FOREIGN CURRENCY CARD',
		'GC-FOR CONNECT CARDS',
		'GM-THE TRA LUONG UU DAI',
		'F1-THE THU PHI THEO GOI DVBL',
		'GS-CARD X - CO.OP MART',
		'GH-X HIWAY',
		'GL-X - LINGO',
		'GE-X - SATRA',
		'MG05-Thẻ từ Etrans',
		'S1-MOVING SILVER CARD',
		'MS06-Thẻ từ Moving',
		'SU-FOR NORMAL CARDS',
		'SY-THE LIEN KET SINH VIEN',
		'MS07-Thẻ từ LK sinh viên',
	],
	'Đặc điểm chi tiết thẻ': [
		'Ngày sao kê: Ngày 20',
		'Ngày sao kê: Ngày 03',
		'Ngày đến hạn thanh toán: 15 ngày sau ngày sao kê',
		'Ngày đến hạn thanh toán: Ngày 08',
		'Số ngày miễn lãi tối đa: 45 ngày',
		'Số ngày miễn lãi tối đa: 35 ngày',
		'Tỷ lệ thanh toán tối thiểu: 5% tổng dư nợ cuối kỳ',
		'Tỷ lệ thanh toán tối thiểu: 3% tổng dư nợ cuối kỳ',
		'Lãi suất 10%',
		'Lãi suất 20%',
		'Lãi suất 18%',
		'Lãi suất 11,5%',
		'Lãi suất 16,5%',
	],
	'Loại thẻ': [
		'Thẻ ghi nợ nội địa cá nhân',
		'Thẻ ghi nợ quốc tế cá nhân',
		'Thẻ trả trước cá nhân',
		'Thẻ ghi nợ doanh nghiệp',
		'Thẻ tín dụng doanh nghiệp',
		'Thẻ dừng phát hành, đang cơ cấu và chuyển phôi',
		'Thẻ tín dụng cá nhân',
		'Thẻ ghi nợ cá nhân',
		'Thẻ ghi nợ nội địa cá nhân phi vật lý',
		'Thẻ ghi nợ nội địa cá nhân vật lý',
		'Thẻ trả trước vô danh',
		'Thẻ trả trước định danh',
	],
	'Tên thẻ': [
		'Thẻ Mastercard Ready',
		'Thẻ Mastercard Discovery',
		'Thẻ liên kết',
		'Thẻ X Smart chip',
		'Thẻ Mastercard Premier mã 12',
		'Thẻ MasterCard Young Plus mã 22-33',
		'Thẻ tín dụng cá nhân các hạng',
		'Thẻ JCB Credit Ultimate',
		'Thẻ ghi nợ và tín dụng doanh nghiệp',
	],
	'Hạng thẻ': [
		'Hạng Chuẩn - Classic',
		'Hạng Bạch Kim - Platinum',
		'Không xác định',
	],
	'Mã BIN': [
		'511957.0',
		'517453.0',
		'970418.0',
	],
	'Độ dài số thẻ': [
		'16 số',
		'19 số',
	],
	'Hình ảnh thẻ': [
		'8637e054-8e2b-4209-892c-df8ebe5f5369_e0cfd3c9f8024f569645c70c9d26e6fd.png',
		'8637e054-8e2b-4209-892c-df8ebe5f5369_f907480c231b4c31a7f5a9fcbf237b4e.jpg',
		'8637e054-8e2b-4209-892c-df8ebe5f5369_e571fde71d8c47d2896cfce4d6305c52.jpg',
		'8637e054-8e2b-4209-892c-df8ebe5f5369_dab0c50f022847db883c11860760942c.jpg',
	],
	'Loại hạn mức': [
		'Số tiền tối đa/lần',
		'Số tiền tối đa/ngày',
		'Số lần tối đa/ngày',
		'Số tiền tối thiểu/lần',
	],
	'Số lần giao dịch/ngày': [
		'20 lần',
		'40 lần',
		'10 lần',
		'99 lần',
		'30 lần',
		'Không giới hạn',
		'0 lần',
		'Bằng Hạn mức giao dịch theo ngày/10^6, tối đa 99 lần',
	],
	'Tên thẻ thay thế': [
		'Thẻ Mastercard Ready',
	],
	'Mã SP tại Corebanking mới': [
		'DP01-OLD_Thẻ Chip VL ACV',
		'DP03-OLD_Thẻ Chip VL ASXH',
		'DS04-OLD_Thẻ Chip VL Liên kết',
		'DG05-OLD_Thẻ Chip Phi Vật lý',
		'DG06-OLD_Thẻ Chip VL online',
		'DG07-OLD_Thẻ Chip VL',
		'DG08-OLD_Thẻ Chip VL CD',
		'DG09-OLD_Thẻ Chip Phi VL',
		'MP01-Thẻ từ ACV',
		'MP02-Thẻ từ Goertek',
		'MP03-Thẻ từ ASXH',
		'MP04-Thẻ từ Harmony',
		'MG05-Thẻ từ Etrans',
		'MS06-Thẻ từ Moving',
		'SU-FOR NORMAL CARDS',
		'SY-THE LIEN KET SINH VIEN',
	],
	'Chi tiết tính năng': [
		'Tích điểm 2% khi giao dịch ngoại tệ và 0.15% với các giao dịch còn lại, trừ giao dịch đặc thù',
		'Cho phép chuyển đổi giao dịch mua sắm hàng hóa, dịch vụ hợp lệ bất kỳ thành giao dịch trả góp với kỳ hạn trả góp và giá trị giao dịch tối thiểu theo quy định của X trong từng thời kỳ',
		'Quyền lợi sử dụng phòng chờ, và các ưu đãi ẩm thực, golf, khách sạn theo chính sách của JCB theo từng thời kỳ',
		'Điện thoại: 1900 9247 - trong nước hoặc 84 24 22200588 - nước ngoài và Email: bidv247@bidv.com.vn',
		'Đối với tổ chức đăng ký phát hành thẻ: Yêu cầu tổ chức đăng ký BSMS cho tất cả thẻ tín dụng doanh nghiệp của tổ chức và thu phí từ tài khoản thanh toán của tổ chức|Đối với cá nhân đang sử dụng BSMS mà không thay đổi SĐT, không phát sinh thêm SĐT khác nhận tin thì thu phí theo gói BSMS cá nhân đã sử dụng|Đối với cá nhân chưa sử dụng BSMS hoặc thay đổi, bổ sung SĐT khác nhận tin: KH trả phí dịch vụ BSMS theo quy định tại biểu phí KHCN từng thời kỳ',
	],
	'Thông tin chi tiết': [
		'Là thẻ do X phát hành gồm Thẻ ghi nợ nội địa - thẻ có BIN do Ngân hàng Nhà nước cấp và Thẻ ghi nợ quốc tế - thẻ có BIN do Tổ chức thẻ quốc tế cấp',
		'Là tài khoản tiền gửi thanh toán cá nhân VND hoặc ngoại tệ USD thuộc sở hữu, sở hữu chung của Chủ thẻ theo quy định từng sản phẩm',
		'Được xác định theo từng loại sản phẩm, loại giao dịch, phạm vi giao dịch|Đối với hạn mức rút ngoại tệ tiền mặt tại nước ngoài, một thẻ được rút số ngoại tệ tối đa tương đương 30 triệu đồng trong 1 ngày|Hạn mức giao dịch thanh toán không tiếp xúc và không cần nhập PIN đối với Thẻ Ghi nợ nội địa là tối đa 500.000VND 1 lần, tối đa 1.000.000VND 1 ngày, không giới hạn số lần 1 ngày',
		'Thanh toán tại quầy|Trích nợ tự động|Chuyển khoản từ ngân hàng khác trong và ngoài nước tới X|Ứng dụng X Smartbanking',
		'Mỗi cá nhân được phát hành 01 thẻ chính cho 1 mã sản phẩm thẻ, mỗi chủ thẻ chính được phát hành tối đa 03 thẻ phụ; chủ thẻ chính và các chủ thẻ phụ phải là các cá nhân khác nhau',
		'Gồm có 12 sản phẩm thẻ chia làm các hạng: hạng cao cấp bao gồm: Infinite, Signature, Ultimate; hạng Platinum; hạng Gold và hạng Classic',
	],
	'Chi tiết hạn mức': [
		'5.000.000 VNĐ',
		'Trong nước: 200.000.000 VNĐ, nước ngoài: 30.000.000 VNĐ',
		'Trong nước: 400.000.000 VNĐ, nước ngoài: 30.000.000 VNĐ',
		'500.000.000 VNĐ',
		'1.000.000.000 VNĐ',
		'10.000.000 VNĐ',
		'100.000.000 VNĐ',
	],
}